### PR TITLE
[Designer] Assign names to icon buttons for Narrator

### LINKED ISSUE #7917: [Adaptive cards> Designer> Card Payload Editor]: Name is not defined for 'Card payload Editor' button.
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS Version: 22H2 (Build 25197.1000)
Browser: Edge Dev (107.0.1379.1)
URL: https://adaptivecards.io/designer/
Screen reader: Narrator

**Repro steps:**

1. Open the above URL in edge dev browser and login with v-.
2. Turn on the narrator through 'Ctrl+ Windows+ Enter key.
3. Navigate to the 'Designer' tab through tab key and activate it.
4. Navigate to the 'Card Payload Editor' button through tab key.
5. Observe the issue.

**Actual Result:**
On Designer tab, Name is not defined for 'Card Payload Editor'. Screen reader is announcing as **'Button Collapsed Show card payload editor'.**

**Expected Result:**
On Designer tab, proper name should be defined for 'Card Payload Editor'. Screen reader should announce as **Card payload editor Button Collapsed Show card payload editor'.**

**Notes:**
Same issue repro with 
1. 'Sample Data Editor', 'Card Structures', 'Element Properties' and 'Feedback' button.

**User Impact:**
Screen reader user will get impacted as user will not be able to understand the purpose of the content and will not be able to navigate or track the content properly.

**MAS Reference link:**
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.02

"Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/104483005/191720807-7711cb27-255b-4bf0-8b21-d90b6ac15273.mp4

Code Snipped~ Card payload editor name is not defined

### Card JSON

```JSON
NA
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue

Fixes #7917 

# Description

Some of the buttons in the Designer did not have an associated accessible name for Narrator.

Toolbox expand/collapse button needed to be labeled by the header text.

Toolbar buttons that only contain an icon need to specify the label.

# How Verified

Verified manually on the Adaptive Cards site.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/7927)

### CODE REVIEW

File: source/nodejs/adaptivecards-designer/src/tool-box.ts [hunk 1]
```diff
@@ -94,6 +94,7 @@ export class Toolbox {
 
         let headerTitleElement = document.createElement("span");
         headerTitleElement.className = "acd-toolbox-header-title";
+        headerTitleElement.id = this.title.replace(/ /g, "-");
```
Comment (licanhua) [inline source/nodejs/adaptivecards-designer/src/tool-box.ts:97]: I would try to avoid this hack way. It may introduce localization and other issue.

also why do you set an id for it?

File: source/nodejs/adaptivecards-designer/src/tool-box.ts [hunk 2]
```diff
@@ -130,6 +131,7 @@ export class Toolbox {
         this._expandCollapseButtonElement.tabIndex = 0;
         this._expandCollapseButtonElement.setAttribute("role", "button");
         this._expandCollapseButtonElement.setAttribute("aria-expanded", "true");
+        this._expandCollapseButtonElement.setAttribute("aria-labelledby", this.title.replace(/ /g, "-"));
```
Comment (licanhua) [inline source/nodejs/adaptivecards-designer/src/tool-box.ts:134]: Can you define a new label for it, instead of deducing it from title.

Comment (anna-dingler) [reply source/nodejs/adaptivecards-designer/src/tool-box.ts:134]: Yes I can do that instead

File: source/nodejs/adaptivecards-designer/src/tool-box.ts (hunk 1 above)
Comment (anna-dingler) [reply source/nodejs/adaptivecards-designer/src/tool-box.ts]: Just updated :)

**Review by licanhua — APPROVED** [review]

**Review by jwoo-msft — APPROVED** [review]
