### PR TITLE
[UWP] Fix issue with nested show cards

### LINKED ISSUE #3177: [UWP] Nested show cards don't work properly
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The following nested show card doesn't work right. Starting with:
image

Click the first button:
image

Click the second button:
image

Click the third button:
image

The third button should show a text block (JS):
image

```
{
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.ShowCard",
          "title": "Action.ShowCard",
          "card": {
            "type": "AdaptiveCard",
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "actions": [
              {
                "type": "Action.ShowCard",
                "title": "Action.ShowCard",
                "card": {
                  "type": "AdaptiveCard",
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "actions": [
                    {
                      "type": "Action.ShowCard",
                      "title": "Action.ShowCard",
                      "card": {
                        "type": "AdaptiveCard",
                        "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                        "body": [
                          {
                            "type": "TextBlock",
                            "text": "New TextBlock"
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

### PR DESCRIPTION
**Pull request by RebeccaAnne**
Show cards were associated with their action set id, with 0 (invalid id) representing the action bar at the bottom of the card. In the case of nested show cards, however, the action bar of the main card and the action bar of any sub cards were all set to action set id 0, causing unexpected behavior when we tried to close all cards with the same action set id.

Fixed this issue by adding InternalIds to cards themselves, and using the card id as the action set id for show cards in the card action bar. This allows us to distinguish between show cards in the main card's action bar and show cards in sub cards' action bars.

How verified: Validated correct behavior with nested show cards in the visualizer and added sample card.

Fixes #3177

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3336)

### CODE REVIEW

File: source/uwp/Renderer/lib/XamlBuilder.cpp [hunk 1]
```diff
@@ -1589,7 +1595,8 @@ namespace AdaptiveNamespace
         return buttonMargin;
     }
 
-    HRESULT XamlBuilder::BuildActionSetHelper(_In_opt_ IAdaptiveActionSet* adaptiveActionSet,
+    HRESULT XamlBuilder::BuildActionSetHelper(_In_ ABI::AdaptiveNamespace::IAdaptiveCard* adaptiveCard,
```
Comment (paulcam206) [inline source/uwp/Renderer/lib/XamlBuilder.cpp]: >_In_  [](start = 46, length = 5)

should be `_In_opt_`?
