### PR TITLE
[WPF][InputEvolution] Copy ParentCardId when a RenderArgs object is cloned

### LINKED ISSUE #4514: [WPF] InputForm.json sample submit doesn't work properly
# Platform

* .NET WPF

# Details

Submit doesn't work correctly on [InputForm.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/InputForm.json).

| New Behavior (release/20.07) | Old Behavior (as of b85dce28af066872d8de419fb7103a0832c29d5a)
| -- | -- |
| image | image |

### LINKED ISSUE #4515: [WPF] Show Card Wizard card not gathering correct inputs
# Platform

.NET WPF

# Details

Inner-most-nested child card submit button isn't gathering all inputs (from our [wizard](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.3/Scenarios/Show%20Card%20Wizard%20(child%20cards).json) sample card).

| New behavior (release/20.07) | Old behavior (as of ) |
| -- | -- |
| image | image |

### PR DESCRIPTION
**Pull request by almedina-ms**
## Related Issue
Fixes #4515
Fixes #4514

## Description
Due to some unexpected circumstance a line of  code was not ported into main, the line cloned the parent card Id which allowed containers, columns and child cards to know the parent card where they were located

## How Verified
The fix was verified manually using the Wizard card 

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4516)

### CODE REVIEW

File: source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java [hunk 1]
```diff
@@ -61,21 +61,6 @@ public static void MoveChildrenViews(ViewGroup origin, ViewGroup destination)
         }
     }
 
-    public static BaseInputElement castToInputElement(BaseCardElement cardElement)
```
Comment (RebeccaAnne) [inline source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java:64]: >BaseInputElement [](start = 18, length = 16)

This file probably doesn't belong in this change

Comment (almedina-ms) [reply source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java]: thanks, I targeted main when I should have targeted release/20.07

**Comment by paulcam206** [comment]
Verified that this fixes #4515 and #4514 🥇

**Comment by shalinijoshi19** [comment]
@paulcam206 is the (.NET-PR [release 1.2]) pipeline supposed to be running for the release/20.07 branch?

**Comment by shalinijoshi19** [comment]
@almedina-ms can you look into the Canceled Android-CI run here?

**Comment by paulcam206** [comment]
> @paulcam206 is the (.NET-PR [release 1.2]) pipeline supposed to be running for the release/20.07 branch?

I already fixed it -- it was set to trigger on `release/*` :)
