### PR TITLE
[iOS] Added error messages in string for Unit Tests

### LINKED ISSUE #6792: Add detailed unit test error messages when parse failed.

### PR DESCRIPTION
**Pull request by jwoo-msft**
# Related Issue
Fixed #6792 

# Description
When the unit test is failed while parsing, current tests don't tell which file failed and why. It requires mac & XCode to debug card issues. By adding the file name, and the reason in the string, PR validation failure can be diagnosed  by 
 anyone who raised PR without needing mac & XCode. 

NSLog is replaced with printf as NSLog can't output to stderr or stdout, and usage of prinf is recommended. 
### [Reference](https://stackoverflow.com/questions/26768855/xcode-ios-testsuite-nslog-output-missing)

# How Verified

How you verified the fix, including one or all of the following:
1. Tested with invalid test cards

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/6793)

### CODE REVIEW

**Review by licanhua — APPROVED** [review]

File: source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm [hunk 1]
```diff
@@ -214,13 +214,17 @@ - (void)parseAndRenderDFS:(NSString *)rootPath FileManager:(NSFileManager *)fMan
                     XCTAssertTrue(renderResult.succeeded);
                 }
                 @catch (NSException *exception) {
-                    NSLog(@"Render Failed while rendering %@\n%@", fileName, exception);
+                    NSString *exceptionMeassage = [NSString stringWithFormat:@"%@", exception];
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm:217]: >exceptionMeassage [](http://example.com/codeflow?start=30&length=17)

typo: exceptionMessage

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCard.mm [hunk 2]
```diff
@@ -78,11 +79,15 @@ + (ACOAdaptiveCardParseResult *)fromJson:(NSString *)payload;
             // converts AdaptiveCardParseException to NSError
             ErrorStatusCode errorStatusCode = e.GetStatusCode();
             NSInteger errorCode = (long)errorStatusCode;
-
+            NSBundle *adaptiveCardsBundle = [[ACOBundle getInstance] getBundle];
+            NSString *localizedFormat = NSLocalizedStringFromTableInBundle(@"AdaptiveCards.Parsing", nil, adaptiveCardsBundle, "Parsing Error Messages");
+            NSString *objectModelErrorCodeInStrig = [NSString stringWithCString:ErrorStatusCodeToString(errorStatusCode).c_str() encoding:NSUTF8StringEncoding];
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCard.mm:84]: >objectModelErrorCodeInStrig [](http://example.com/codeflow?start=22&length=27)

typo: objectModelErrorCodeInString

**Review by almedina-ms — APPROVED** [review]
:shipit:

**Review by paulcam206 — APPROVED** [review]
