### PR TITLE
[Android] Input labels and errors support

### LINKED ISSUE #4235: [Android] Action.Submit crashes when no inputs
# Platform

* Android

# Details

Using the card [Action.ShowCard.json] (https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Elements/Action.ShowCard.json) the android mobile app crashes when the "Neat" button is clicked

### LINKED ISSUE #4237: [Android] Only input elements are rendered
# Platform

* Android

# Details

Any element that doesn't have a label or an errorMessage are not being rendered/shown. This is related to changes introduced in the current version

### LINKED ISSUE #4240: [Android] TextBlock is not being aligned
# Platform

* Android

# Details

TextBlocks are not respecting the horizontal alignment

Screenshot_20200626-171702_AdaptiveCards Visualizer

Screenshot_20200626-172559_AdaptiveCards Visualizer

### LINKED ISSUE #4242: [Android][Input Evolution] [Num Keypad Issue]
# Platform

What platform is your issue or question related to? (Delete other platforms).
* Android

# Version of SDK
1.3

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

# Details
[Payload](https://github.com/microsoft/AdaptiveCards/blob/user/almedina-ms/AndroidInputEvolution/samples/v1.3/Elements/Input.Number.ErrorMessage.json)

1. Touch input with id,  "input4". 
2. Num Keypad appears
3. If you press '-', nothing will appear in the screen.

### LINKED ISSUE #4243: [Android] ColumnFallback card renders nothing
# Platform

* Android

# Details
 
[ColumnFallback](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.2/Elements/Column.Fallback.json) is not rendering any element. It should render two columns as those are the fallbacks

Screenshot_20200626-174435_AdaptiveCards Visualizer

### PR DESCRIPTION
**Pull request by almedina-ms**
## Related Issue
Part of #3081

Also as part of bug bashes:
Fixes #4243 
Fixes #4242 
Fixes  #4240 
Fixes #4237 
Fixes #4235 

## Description
Adds support for Labels and Input Validation for the Adaptive Cards android renderer.

This PR includes changes to the java interfaces as a new version of swig was used to generate them.

This change also includes the beginning of the roll out of the new version of tests which allows unit tests to be more concise and reduces the size of each of the test methods.

Finally, some custom layouts were added to remove repetition for height scenarios and a new layout to contain the label, input and error message. This makes it easier to show and hide the error message.

## How Verified
How you verified the fix, including one or all of the following: 
1. New unit tests were added for the new properties. Also the modified tests were also tested
2. The behaviour and rendering were tested manually (images to be added)
will aid in code reviews or corresponding fixes on other platforms for eg.***

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4039)

### CODE REVIEW

File: source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/InputUtil.java [hunk 1]
```diff
@@ -0,0 +1,155 @@
+package io.adaptivecards.renderer.input;
```
Comment (paulcam206) [inline source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/InputUtil.java:1]: missing copyright banner

**Comment by shalinijoshi19** [comment]
@almedina-ms can you check why the Android builds are failing and then go ahead check this into feature/inputEvolution ? Thanks!
