### PR TITLE
Fixed Overflow action button not announcing view chagnes

### LINKED ISSUE #8654: {Linked:Bug3118618} [Adaptive Cards > Action.Toggle Visibility] - Screen Reader is not conveying the 'Expanded/Collapsed' state for the more option button.
### Target Platforms

Other

### SDK Version

1.0

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/explorer/Action.ToggleVisibility.html
OS Version: 23H2(OS Build 25915.1000)
Browser Version: Edge Dev 117.0.2033.0
Screen Reader: Narrator

**Repro Steps:**
1. Open the URL on Edge Dev browser.
2. Press tab key and navigate to the 'More Option' button under 'Please confirm your data'.
3. Press enter key and observe the issue.

**Actual Result:**
While navigating to the 'More Option' button on pressing enter key, screen reader is not conveying the state information as 'Expanded'. It is simply announcing the information about the items present under it.

**Expected Result:**
Screen reader should convey the state information when user activates the 'More Option' button. It should announce as **'More Option button expanded then it should announce the items present under it.'**

**User Impact:**
Users who rely on screen readers will be affected if screen reader does not announce expand/collapsed state info for the controls present in the Action.toggle visibility screen. Due to this user will get confused and will not get idea that control is getting expanded/collapsed and this may cause distortion.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/sites/accessibility/_layouts/15/Doc.aspx?sourcedoc=%7B507B5D90-F1B9-4AE1-91D1-2F1F2D6C7C1D%7D&file=MAS%204.1.2%20%E2%80%93%20Name%2C%20Role%2C%20Value.docx&action=default&mobileredirect=true&share=IQGQXXtQufHhSpHRLx8tbHwdAUoz-PLo6lZ2eagKqmDeOGc

Have feedback to share on Bugs? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fforms.office.com%2fpages%2fresponsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-ssachan%40microsoft.com%7c68d0243104da4caeb08708d9ba4d6c6b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637745663988426007%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=YMsEOknKWOki3Fi%2BatsKabxS%2BM1tfTrgnws52jzpI7M%3D&reserved=0).

### Screenshots

https://github.com/microsoft/AdaptiveCards/assets/95913748/6ae158f0-a128-454c-b0e1-607665c50439

### Card JSON

```JSON
NA
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### PR DESCRIPTION
**Pull request by jwoo-msft**
# Related Issue
Fixed #8654.

# Description
As focus is moved to a menu overlay from a button, buttons aria-expanded state is not announced by voice over. moved the aria-expanded to menu item itself, where the focus is set. When menu item closes, have the focus to be back on the button with aria-expanded set to false. however, with keyboard navigation, when 'return' key is used to close the menu item, it will trigger click event on the button when the focus is back to the button. In order to stop such behavior, preventDefault() was used.

# Sample Card
N/A

# How Verified

Manually verified.

### CODE REVIEW

File: source/nodejs/adaptivecards/src/controls/popup-menu.ts [hunk 1]
```diff
@@ -101,4 +108,14 @@ export class PopupMenu extends PopupControl {
...
         }
     }
+
+    // remove aria-expanded attribute from menu item
+    private removeAriaExpanded(index: number) {
+        if (this._renderedItems[index].getAttribute("aria-expanded") === "true") {
+            this._renderedItems[index].removeAttribute("aria-expanded");
+        }
+    }
+
```
Comment (anna-dingler) [inline source/nodejs/adaptivecards/src/controls/popup-menu.ts:118]: nit: extra new lines

**Review by anna-dingler — APPROVED** [review]

File: source/nodejs/adaptivecards/src/controls/popup-menu.ts [hunk 2]
```diff
@@ -21,6 +21,11 @@ export class PopupMenu extends PopupControl {
 
             element.appendChild(renderedItem);
 
+            if (i == 0)
+            {
+                renderedItem.setAttribute("aria-expanded", "true");
+            }
+
             if (i === this.selectedIndex) {
```
Comment (anna-dingler) [inline source/nodejs/adaptivecards/src/controls/popup-menu.ts:29]: nit: I'm wondering if we should set "aria-expanded" on the focused element?

Also FWIW, we might want to revisit this again later, because expanded is announced each time this menu item receives focus. I'm not sure it should be announced while navigating the list, only when the menu is first expanded.

Comment (jwoo-msft) [reply source/nodejs/adaptivecards/src/controls/popup-menu.ts:29]: @anna-dingler ,

navigating using keys up and down will remove the aria-expanded. when the menu item is rendered, we set the first item to be in focus.

Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/controls/popup-menu.ts:29]: Interesting, only commented on it because I saw the behavior on the test site. Not sure why, but it works correctly in regular mode, and doesn't work in scan mode.

Not blocking or anything though :)

Comment (jwoo-msft) [reply source/nodejs/adaptivecards/src/controls/popup-menu.ts:29]: @anna-dingler, thanks, i will sync up with you offline.
