### PR TITLE
[Android] Fix height: stretch elements in columns

### LINKED ISSUE #4989: [Android][Rendering] Elements with "height: stretch" cause other elements to vertically shrink
# Platform

What platform is your issue or question related to? (Delete other platforms).

- [ ] Android

# Version of SDK

main

# Details

With the revert of the constraint layout bump, an issue was unearthed in v1.2/Tests/ImageSizing.json. This bug makes some images in columns to use more height space than it should, making other elements in the column  too small (in height) to be visible

image

Another example:

`v1.1\Tests\ColumnSet.VerticalStretch.json`:

image

### PR DESCRIPTION
**Pull request by golddove**
## Related Issue
Fixes #4989 

## Description
Elements that use `LinearLayout.LayoutParams` to set weight for vertical stretch fail when those elements are laid out in a FlexboxLayout. There is actually no reason for ColumnRenderer to use flexbox, it just needs the right flex properties set so the ColumnSetRenderer flexbox can correctly layout the child columns. So, reverting to use LinearLayout for ColumnRenderer.

## Sample Card
(most samples were modified for these screenshots by shortening the text)

`v1.1\Tests\ColumnSet*`
image
image
image
image
image
image
image
image
image
image
image

`v1.1\Tests\Column.VerticalAlignment`
image

`v1.2\Elements\Column.MinHeight`
image

`v1.2\Elements\ColumnSet.MinHeight`
image

## How Verified
Screenshots above

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5085)

### CODE REVIEW

File: source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java [hunk 1]
```diff
@@ -73,19 +73,17 @@ public View render(
...
-        }
-
         ContainerStyle parentContainerStyle = renderArgs.getContainerStyle();
         ContainerStyle styleForThis = ContainerRenderer.GetLocalContainerStyle(columnSet, parentContainerStyle);
 
         for (int i = 0; i < columnVectorSize; i++)
         {
             Column column = columnVector.get(i);
 
+            if(columnSet.GetMinHeight() > column.GetMinHeight()) {
```
Comment (RebeccaAnne) [inline source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java:83]: >{ [](start = 65, length = 1)

[nit] for style consistency with the rest of this code let's put this brace on the next line

**Review by RebeccaAnne — APPROVED** [review]
:shipit:
