### PR TITLE
[JS Renderer] Update accessibility for OverflowAction

### LINKED ISSUE #7867: [Adaptive Cards-Schema Explorer]: Name is not defined for the "more options" button.
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Screen Reader: Narrator
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Run the Narrator using "Control+ Windows +Enter" short key in the scan mode.

Repro Steps:
1.Open above URL with V- credential.
2.On the Narrator using "Control+Windows +Enter" short key.
2.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
3.Navigate to 'Action.Togglevisibility" link present under Actions from the left navigation using the tab key and activate it using Enter key.
4. Navigate to the adaptive cards present under it using the Tab key.
5. Navigate to the "please confirm your data" heading under Adaptive Cards using Tab key.
6. Navigate using tab key through the buttons present under it using narrator.
7. Observe the issue at "..." button.

Actual Result:
Narrator is announcing it as just button not giving any name with it.

Expected Result:
"..." button should have a name defined for it as more options button so that narrator will announce it as "More Options Button".

User Experience:
Screen reader users will be impacted if there is no name defined for the button and they will not be able to understand the usage of that particular control.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.02

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

5 name should be defined for   as more option button

https://user-images.githubusercontent.com/104482612/190376347-672beeb1-6459-4741-9ca3-cb16a918910b.mp4

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

### LINKED ISSUE #7868: [Adaptive Cards-Schema Explorer]: state is not announced by the narrator when the button is expanding/Collapsing.
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

Test Environment:
OS: Version 22H2 (OS Build 25197.1000)
Edge Dev: version 107.0.1379.1 (Official build) dev (64-bit)
Screen Reader: Narrator
Application URL: [[[https://adaptivecards.io/](https://nam06.safelinks.protection.outlook.com/?url=https://adaptivecards.io/&data=04%7c01%7cv-ibalam%40microsoft.com%7cbd35d875ec3f4539762308d88f709775%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637417061036711036%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=dUolQbKGi1J8gsoxC2JG5TGoNi41msPfIIjKSIyPGHM%3D&reserved=0)]([https://adaptivecards.io/explorer/)](https://adaptivecards.io/%5D(https://adaptivecards.io/explorer/)%5D(https://adaptivecards.io/))

Pre-Requisites:
Run the Narrator using "Control+ Windows +Enter" short key in the scan mode.

Repro Steps:
1.Open above URL with V- credential.
2.On the Narrator using "Control +Windows +Enter" short key.
3.Navigate to 'Schema Explorer' link using tab key and press enter key to activate it.
4.Navigate to 'Action.Togglevisibility" link present under Actions from the left navigation using the tab key and activate it using Enter key.
5. Navigate to the adaptive cards present under it using the Tab key.
6. Navigate to the "please confirm your data" heading under Adaptive Cards using Tab key.
7. Navigate using tab key through the buttons present under it using narrator.
8. Navigate to the "..." button and activate it using Enter key and observe the issue. 

Actual Result:
Narrator is announcing the state of the button when it got expanded/Collapsed.

Expected Result:
Narrator should give the state of the button when it got expanded/collapsed as more option button got expanded/collapsed.

User Experience:
Screen reader users will be impacted if state is not announced by the narrator as user will not be able to understand whether button got collapsed or expanded.

MAS Reference:
https://liquid.microsoft.com/Web/Object/Read/MS.Accessibility/Requirements/04.01.03

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “.

### Screenshots

https://user-images.githubusercontent.com/104482612/190392309-76aa2f14-5ad6-4e5d-97af-fb05b21a6926.mp4

### Card JSON

```JSON
NA
```

### Sample Code Language

NA

### Sample Code

NA

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue

Fixes #7868
Fixes #7867 

# Description

For OverflowAction, we needed to:
- Add a tooltip `More options`
- Override `setupElementForAccessibility` so that we can assign `aria-expanded` and `aria-label`
- Update `aria-expanded` when we display and close the popup.

# Sample Card

```JSON
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.5",
  "body": [
    {
      "type": "TextBlock",
      "text": "Please confirm your data:",
      "wrap": true,
      "style": "heading"
    },
    {
      "type": "FactSet",
      "facts": [
        {
          "title": "First Name",
          "value": "John"
        },
        {
          "title": "Last Name",
          "value": "Smith"
        },
        {
          "title": "Phone number ",
          "value": "(555) 555-5555"
        }
      ]
    }
  ],
  "actions": [
    {
      "type": "Action.Execute",
      "title": "Confirm data"
    },
    {
      "type": "Action.Execute",
      "title": "Edit data",
      "data": "edit",
      "mode": "secondary"
    },
    {
      "type": "Action.Execute",
      "title": "Delete data",
      "data": "delete",
      "mode": "secondary"
    }
  ]
}
```

# How Verified

Verified manually on the Adaptive Cards site.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/7940)

### CODE REVIEW

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 1]
```diff
@@ -5708,9 +5709,23 @@ class OverflowAction extends Action {
                 contextMenu.items.add(menuItem);
             }
 
+            contextMenu.onClose = () => {
+                if (this.renderedElement) {
+                    this.renderedElement.ariaExpanded = "false";
```
Comment (paulcam206) [inline source/nodejs/adaptivecards/src/card-elements.ts:5714]: Sadly, Firefox [doesn't yet support](https://caniuse.com/mdn-api_element_arialabel) `aria` mixins, so you'll need to drop back to using `get/setProperty` like we do elsewhere. ☹️ 

e.g.

```suggestion
                    this.renderedElement.setProperty("aria-expanded", "false");
```

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 2]
```diff
@@ -5708,9 +5709,23 @@ class OverflowAction extends Action {
...
+                }
```
Comment (paulcam206) [inline source/nodejs/adaptivecards/src/card-elements.ts:5715]: alternatively could write as 

```suggestion
                this.renderedElement?.ariaExpanded = "false";
```

**Review by paulcam206 — CHANGES_REQUESTED** [review]

File: source/nodejs/adaptivecards/src/card-elements.ts (hunk 1 above)
Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts:5714]: I didn't know that - thanks for letting me know!

File: source/nodejs/adaptivecards/src/card-elements.ts (hunk 2 above)
Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts]: This didn't work originally because you can't do property assignment on an optional variable. I just updated to use `setAttribute` here as well :)

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 3]
```diff
@@ -5708,9 +5709,21 @@ class OverflowAction extends Action {
...
+
+            this.renderedElement.setAttribute("aria-expanded", "true");
             contextMenu.popup(this.renderedElement);
         }
     }
+    
+    setupElementForAccessibility(element: HTMLElement, promoteTooltipToLabel: boolean = false) {
+        super.setupElementForAccessibility(element, promoteTooltipToLabel);
+
+        element.ariaLabel = Strings.defaults.overflowButtonTooltip();
```
Comment (paulcam206) [inline source/nodejs/adaptivecards/src/card-elements.ts:5724]: missed one :)

```suggestion
        element.setAttribute("aria-label", Strings.defaults.overflowButtonTooltip());
```

**Review by paulcam206 — CHANGES_REQUESTED** [review]
