### PR TITLE
[iOS] Updated vertical content alignment, height and toggle Visibility

### LINKED ISSUE #2839: [.NET] Vertical Alignment of background image doesn't work
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET WPF

# Issue

The below card doesn't render correctly. The background image should be centered because verticalAlignment is set to center:

Expected behavior [TS]:
image

Actual behavior [.NET]:

image

The image being used looks like this:
image

```
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.2",
	"backgroundImage": {
		"url": "https://picsum.photos/60/60?image=101",
		"verticalAlignment": "center"
	},
	"body": [
		{
			"type": "TextBlock",
			"text": "Text in body"
		},
		{
			"type": "ColumnSet",
			"columns": [
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"text": "Text in Column 1"
						}
					]
				},
				{
					"type": "Column",
					"width": "auto",
					"items": [
						{
							"type": "TextBlock",
							"text": "Text in Column 2"
						}
					]
				}
			]
		},
		{
			"type": "Container",
			"items": [
				{
					"type": "TextBlock",
					"text": "Text 1 in Container"
				},
				{
					"type": "TextBlock",
					"text": "Text 2 in Container"
				},
				{
					"type": "TextBlock",
					"text": "Text 3 in Container"
				}
			]
		}
	]
}
```

### LINKED ISSUE #2942: [iOS][BugBash] Vertical Stretch Doesn't Work Properly
# Platform

What platform is your issue or question related to? (Delete other platforms).
* iOS

# Issue

https://github.com/microsoft/AdaptiveCards/blob/master/samples/Tests/ColumnSet.AllElements.Stretch.ToggleVisibility.json
**JSON**

Screenshot_1558127825
**Figure 1**

Simulator Screen Shot - iPhone 6s - 2019-05-17 at 14 17 38
**Figure 2**

There is vertical stretch in Figure 2 where it shouldn't be as in Figure 1. 

Although not shown in the screen capture, input items in 2nd ColumnSet do not respect the alignment. i.e. it has spaces but not aligned properly or aligned differently compared to Android.

### LINKED ISSUE #3749: [iOS][BugBash] [Vertical Content Alignment for Adaptive Card Not Working]
# Platform
* iOS

# Version of SDK
1.2.6

# Details
Expected Behavior 
on JS
image

Actual Behavior
on iOS 
image

### LINKED ISSUE #4063: [IOS][Layout] [Extra UIView in the container with only 1 ColumnSet element, and sometimes this cause extra space for the card]
# Platform

IOS

# Author or host

Host - Teams IOS

# Version of SDK

Both SDK 1.2.7 and the latest master

# Details

We want to show several items on one card. For the first item, it is one Container with only one ColumnSet element. The payload is shown below.

```
{
  "type": "Container",
  "items": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "large",
              "text": "Backup2 on-call schedule for the [Cortana Experience\\Cortana on Android/iOS CoA/CoI Cortana Exp China DRI] team",
              "wrap": true,
              "maxLines": 2,
              "spacing": "medium"
            },
            {
              "type": "TextBlock",
              "isSubtle": true,
              "text": "Today, 9:00 AM - Tomorrow, 12:00 AM",
              "spacing": "none"
            }
          ]
        }
      ]
    }
  ]
}
```
But sometimes, for the same payload, the first item would have an extra space UIView like this.
Screenshot (1)

After investigation, I find that every container would have an extra UIView. Attached the payload.
[new_payload.txt](https://github.com/microsoft/AdaptiveCards/files/4694605/new_payload.txt)

In most cases, the extra UI view's height would be zero and won't affect UI, but not sure why sometimes, it would extend height to 20.5px.

Screen Shot 2020-05-28 at 5 10 39 PM
Screen Shot 2020-05-28 at 4 49 32 PM
Screen Shot 2020-05-28 at 4 49 45 PM
Screen Shot 2020-05-28 at 4 50 19 PM

The UI view could also be found with the Adaptive card latest master branch.

### LINKED ISSUE #6083: [Rendering] [Inconsistency] verticalContentAlignment property is not working as expected
# Target Platform

- iOS

# Target Application

Microsoft Teams

# Problem Description

We can specify `verticalContentAlignment` as top, bottom or center but it is not working on iOS as expected. It defines how the content should be aligned vertically within the container.
Content is not aligned properly and is always aligned at the bottom irrespective of the property value. Card rendered well on android, desktop and adaptive card designer too but not on iOS.

This issue is reproing on SDK sample app (Visualiser) also on latest main branch.

# Screenshot

iOS 

Screenshot 2021-07-14 at 11 51 20 AM

Desktop (card renders as expected)
Screenshot 2021-07-14 at 11 13 49 AM

# Card JSON
```json
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "text": "Hey",
      "wrap": true,
      "horizontalAlignment": "Right",
      "weight": "Bolder",
      "size": "ExtraLarge",
      "color": "Good"
    },
    {
      "type": "TextBlock",
      "text": "Hlo",
      "wrap": true,
      "horizontalAlignment": "Right",
      "weight": "Bolder",
      "size": "ExtraLarge",
      "color": "Good"
    }
  ],
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "minHeight": "400px",
  "verticalContentAlignment": "center"
}
```
# Sample Code

# Version of SDK
v1.2

### PR DESCRIPTION
**Pull request by jwoo-msft**
# Related Issue
Fixed #6083, Fixed #4063, Fixed #2942, Fixed #2839, Fixed #3749

# Description

### Problem Description
* UIStackView doesn't support alignment perpendicular to a distribution axis; this makes implementation of vertical content alignment difficult. The UIStackView fills the available spaces by stretching subviews. To implement the alignment, a spacer view is necessary, however, this creates few issues. Combined with toggle visibility, spacer view has to be tracked and managed along with the separator. We have to be careful about when to add a spacer as well, and setting constraints for the padding has to be updated when views change their visibility along with their intrinsic content size.
### Changes Description
* This pr adds two new modules, spacer manager and visibility manager.
* spacer manager tracks the padding and their owner
* spacer manager configures padding's hugging and stretch properties along with associated constraints.
* visibility manager manages visibility changes
* it maintains an ordered list of visible views, and the first element is the head
* its order is maintained, and search and insertion is done via binary search.
* when a new head view is added to and removed from the visible view list, the visibility manager does what's necessary.
* In other cases, changing visibility is simple. 

# Sample Card

# How Verified

How you verified the fix, including one or all of the following:
1. new unit tests are added
2. all scenario cards and relevant sample cards were run.

125573128-22647d17-a94e-4d83-b0b0-461c82003603

Screen Shot 2021-09-15 at 4 57 23 PM

Screen Shot 2021-09-15 at 10 44 57 PM
Screen Shot 2021-09-15 at 10 45 19 PM

Screen Shot 2021-09-15 at 10 45 42 PM
Screen Shot 2021-09-15 at 4 57 47 PM

Screen Shot 2021-09-15 at 10 41 09 PM
Screen Shot 2021-09-15 at 10 40 01 PM

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/6329)

### CODE REVIEW

**Review by paulcam206 — APPROVED** [review]

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.h [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+/// if it's not possible
+- (NSArray<NSLayoutConstraint *> *)activateConstraintsForPadding;
+
+- (void)deActivateConstraintsForPadding;
+
+- (BOOL)isPadding:(UIView *)padding;
+
+- (NSArray<NSValue *> *)getFillerSpaceView:(UIView *)view;
+
+- (void)associateSeparatorWithOwnerVew:separator ownerView:ownerView;
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.h:42]: >associateSeparatorWithOwnerVew [](http://example.com/codeflow?start=8&length=30)

typo: associateSeparatorWithOwnerView

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+//  AdaptiveCards
+//
+//  Copyright © 2021 Microsoft. All rights reserved.
+//
+//
+
+#import "ACOFillerSpaceManager.h"
+#import "ACOBaseCardElementPrivate.h"
+
+const CGFloat kFillerViewLayoutConstraintPriority = UILayoutPriorityDefaultLow - 10;
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:12]: >10 [](http://example.com/codeflow?start=81&length=2)

why has this value of 10 picked? does this value matter at all?

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm [hunk 3]
```diff
@@ -0,0 +1,171 @@
...
+        if (_paddingConstraints && _paddingConstraints.count) {
+            [NSLayoutConstraint activateConstraints:_paddingConstraints];
+        }
+
+        return _paddingConstraints;
+    }
+    return nil;
+}
+
+- (void)deActivateConstraintsForPadding
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:131]: >deActivateConstraintsForPadding [](http://example.com/codeflow?start=8&length=31)

possible rename to deactivateConstraintsForPadding

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm [hunk 4]
```diff
@@ -0,0 +1,171 @@
...
+
+- (NSArray<NSValue *> *)getFillerSpaceView:(UIView *)view
+{
+    if (_paddingMap) {
+        return [_paddingMap objectForKey:view];
+    }
+    return nil;
+}
+
+- (void)associateSeparatorWithOwnerVew:separator ownerView:ownerView
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:154]: >separator ownerView:ownerView [](http://example.com/codeflow?start=39&length=29)

why does this function doesn't have associated datatypes to its parameters?

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm [hunk 5]
```diff
@@ -7,112 +7,212 @@
...
-    } else if (index - 1 >= 0) {
-        NSInteger prevViewIndex = index - 1;
-        UIView *prevView = subviews[prevViewIndex];
-        if ([prevView isKindOfClass:[ACRSeparator class]]) {
-            if (!prevView.isHidden) {
-                prevView.hidden = YES;
-            }
-        }
+/// YES means the index of view is currently the leading or top view
+- (BOOL)amIHead:(NSUInteger)index
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:73]: >amIHead [](http://example.com/codeflow?start=8&length=7)

possible rename to isIndexedItemHead/Leading/Top or something similar

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm [hunk 6]
```diff
@@ -7,112 +7,212 @@
...
-        for (UIView *subview in subviews) {
-            if (!subview.isHidden && ![subview isEqual:self.padding]) {
-                return;
-            }
+    return NSNotFound;
+}
+
+/// change the visibility of the separator of a host view to `visibility`
+/// `visibility` `YES` indicates that the separator will be hidden
+- (void)changeVisiblityOfSeparator:(UIView *)hostView visibilityValue:(BOOL)visibility contentStackView:(ACRContentStackView *)contentStackView
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:91]: >visibility [](http://example.com/codeflow?start=76&length=10)

I feel like visibility is tied to the possibility of seeing/detecting an element, it's odd to have it tied to the hidden value, this could be fixed by negating the visibility value or renaming the parameter

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm [hunk 7]
```diff
@@ -7,112 +7,212 @@
...
+            [hostView increaseIntrinsicContentSize:viewToBeUnhidden];
+        }
+        [self changeVisiblityOfAssociatedViews:viewToBeUnhidden visibilityValue:NO contentStackView:hostView];
     }
 }
 
+- (void)updatePaddingVisibility
+{
+    [_fillerSpaceManager deActivateConstraintsForPadding];
+    [_fillerSpaceManager activateConstraintsForPadding];
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:216]: why is this happening? is it a rest or a refresh of some kind?

**Review by almedina-ms — CHANGES_REQUESTED** [review]
:clock1:

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm (hunk 6 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:91]: The name of the visibility property of UIView is hidden.
If Set YES, the view will be hidden.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm (hunk 3 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:131]: fair enough

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm (hunk 2 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:12]: constraints with this priority will be overridden if there are competing constraints. UIKit puts default low for its low priority constraints.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm (hunk 4 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm:154]: i don't follow you.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm (hunk 7 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:216]: visibility & padding changes are not done by the filler space manager. fillersapcemanger deactivates the old constraints. and activate new constraints changes from the visibility manager.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm (hunk 5 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:73]: thanks for the suggestion.  i will keep it as it is as the suggested change doesn't drastically improve what's here.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm (hunk 4 above)
Comment (almedina-ms) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm]: take for example the function at line 159, the function is defined as 

- <return type> <function name>: (<parameter data type>) <parameter name>

in the case of this function the (<parameter data type>)  is not being declared

Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOFillerSpaceManager.mm]: good catch

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm (hunk 6 above)
Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOVisibilityManager.mm:91]: fair enough

**Review by almedina-ms — APPROVED** [review]
:shipit:
