### PR TITLE
Fixed data uri background image

### LINKED ISSUE #3636: [iOS]Background DataUri is not working
# Platform

* iOS

# Version of SDK

Release 1.2 branch

# Details

The v1.1/Elements/AdaptiveCard.BackgroundImage.DataUri card does not render the background image. Other Data uri cards are able to show the pictures correctly.

### PR DESCRIPTION
**Pull request by nesalang**
## Related Issue
Fixed #3636 

## Description
Sample app fails to render data uri background image. This change registers "data" scheme to resource resolvers, so the data uri background image will work through resource resolver. 

## How Verified
Checked for regression.
Verified with test images
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3817)

### CODE REVIEW

**Comment by RebeccaAnne** [comment]
Could you update the description to give more detail on what the issue was and how your code change fixes it? Thanks!

File: source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m [hunk 1]
```diff
@@ -121,6 +121,7 @@ - (void)viewDidLoad
     ADCResolver *resolver = [[ADCResolver alloc] init];
     [_resolvers setResourceResolver:resolver scheme:@"http"];
     [_resolvers setResourceResolver:resolver scheme:@"https"];
+    [_resolvers setResourceResolver:resolver scheme:@"data"];
```
Comment (shalinijoshi19) [inline source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m]: Do we have unit tests for this code path today that can run as part of CI (so automated unittests-based verification rather than manual functional/end-end)?

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm [hunk 2]
```diff
@@ -84,8 +84,7 @@ void renderBackgroundImage(const std::shared_ptr<AdaptiveCards::BackgroundImage>
 
         if (imgView) {
             imgView.translatesAutoresizingMaskIntoConstraints = NO;
-            [containerView addSubview:imgView];
-            [containerView sendSubviewToBack:imgView];
+            [containerView insertSubview:imgView atIndex:0];
```
Comment (shalinijoshi19) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm]: >containerView [](start = 13, length = 13)

What happens today? And what will happen after this change, to the current view at index0 that may already be there?

**Comment by shalinijoshi19** [comment]
>                 // (ACRView::observeValueForKeyPath)

Why commented out? Is this still relevant? If not let's remove the commented out statement altogether. If the comment is needed, let's add a comment explaining hte comment :) - ideally though we wouldnt have stray commented out lines of code in general

---
Refers to: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm:91 in c070461. [](commit_id = c070461555bd7c8d7c0b062a46163cdc30fc078a, deletion_comment = False)

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm [hunk 3]
```diff
@@ -303,7 +302,7 @@ void applyBackgroundImageConstraints(const BackgroundImage *backgroundImagePrope
                 isDeficientInHeight = YES;
             }
 
-            if (isDeficientInWidth and isDeficientInWidth) {
+            if (isDeficientInWidth and isDeficientInHeight) {
```
Comment (shalinijoshi19) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm]: >cientInWidth and isDeficientInHei [](start = 22, length = 33)

ha! good catch. How do we catch bugs like these sooner rather than later? Can we have a unit test added that will invoke this code path? Also do we have an end-end functional/scenario sample that tests this out? If not let's get it added/test results updated for the UWP app etc.

File: source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m (hunk 1 above)
Comment (nesalang) [reply source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m]: No, we don't have it. I will add it.

---
In reply to: [387934866](https://github.com/microsoft/AdaptiveCards/pull/3817#discussion_r387934866) [](ancestors = 387934866)

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm (hunk 2 above)
Comment (nesalang) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm]: This is merely cosmetic. the codes do essentially same. 

---
In reply to: [387940578](https://github.com/microsoft/AdaptiveCards/pull/3817#discussion_r387940578) [](ancestors = 387940578)

**Comment by nesalang** [comment]
Thanks for brining up. I updated it. 

---
In reply to: [594727254](https://github.com/microsoft/AdaptiveCards/pull/3817#issuecomment-594727254) [](ancestors = 594727254)

**Comment by shalinijoshi19** [comment]
>                 // (ACRView::observeValueForKeyPath)

Still see it?

---
In reply to: [594851650](https://github.com/microsoft/AdaptiveCards/pull/3817#issuecomment-594851650) [](ancestors = 594851650)

---
Refers to: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm:91 in c070461. [](commit_id = c070461555bd7c8d7c0b062a46163cdc30fc078a, deletion_comment = False)

**Comment by nesalang** [comment]
>                 // (ACRView::observeValueForKeyPath)

updated it now; thanks!

---
In reply to: [597398880](https://github.com/microsoft/AdaptiveCards/pull/3817#issuecomment-597398880) [](ancestors = 597398880,594851650)

---
Refers to: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm:91 in c070461. [](commit_id = c070461555bd7c8d7c0b062a46163cdc30fc078a, deletion_comment = False)

**Comment by shalinijoshi19** [comment]
Is the title for the PR accurate still?

**Comment by nesalang** [comment]
> Is the title for the PR accurate still?

it's still accurate, but i changed it to more precise title.
