### PR TITLE
Designer surface a11y updates

### LINKED ISSUE #8825: {Linked:Bug3397200}[Adaptive Cards > Designer] - Screen Reader does not announce the information as Empty Adaptive card.
### Target Platforms

Other

### SDK Version

1.6

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/designer/
OS Version: 23H2 (OS Build 26040.1000)
Browser Version: Version 122.0.2365.3 (Official build) dev (64-bit)
Screen Reader: Narrator

**Repro Steps:**
1. Open the above URL on Edge Dev URL.
2. Press tab key and navigate to the 'New Card' and press enter key to activate it.
3. New Card dialog will be appeared.
4. Navigate to the 'Blank Card' using tab key and press enter key to activate it.
5. Navigate to the 'Empty Adaptive Card' and observe the issue.

**Actual Result:**
Screen Reader does not announce the information as Empty Adaptive card, it announces as 'Card preview region Group' but does not announce that it is empty,
Also, Screen reader is announcing the infomration as Group only.

**Expected Result:** 
Screen Reader must announce the complete information as Card preview region group adaptive card empty clickable.
Also, when there is any label present then it should announce the label infomration as well.

**Observation:**
Issue is also repro with NVDA.

**Note:**
1. While navigating in backward navigation it is announcing the information as 'Blank'.
2. Same issue is observed when user is navigating to controls present under Editor section. Screen Reader is conveying only as  "Group" and "Double click to edit group".

**User Experience:**
Users who rely on screen readers will not get the proper information that the card is empty, and no action will occur when they press enter and so they may get confused and face trouble in accessing the UI properly.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

Have feedback to share on Bugs ? please tag bug as “A11yRCA” and add your feedback in the comment section

### Screenshots

Screen Reader does not announce the information as Empty Adaptive card

https://github.com/microsoft/AdaptiveCards/assets/95913748/c5a277df-7bb2-4c04-b094-dc80d1780385

### Card JSON

```JSON
NA
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### LINKED ISSUE #8826: {Linked:Bug3397279}[Adaptive Cards > Designer] - The menu item appears after expanding the 'Add an action' button is not accessible with keyboard.
### Target Platforms

Other

### SDK Version

1.6

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/designer/
OS Version: 23H2 (OS Build 26040.1000)
Browser Version: Version 122.0.2365.3 (Official build) dev (64-bit)
Screen Reader: Narrator

**Repro Steps:**
1. Open the above URL on Edge Dev URL.
2. Press tab key and navigate to the 'New Card' and press enter key to activate it.
3. New Card dialog will be appeared.
4. Navigate to the 'Blank Card' using tab key and press enter key to activate it.
5. Navigate to the 'Add an Action' button and press enter key to activate it.
6. Press tab or arrow key and observe the issue.

**Actual Result:**
The menu item appears after expanding the 'Add an action' button is not accessible with keyboard, on pressing down arrow key focus does not move inside the menu items and after pressing tab key focus moves to the next control and the menu item remains expanded.

**Expected Result:** 
The menu item appears after expanding the 'Add an action' button should be accessible with keyboard up/down arrow keys and after pressing tab focus should land on next control and the menu item should collapse.

**Note:**
After adding any item from the add an action with mouse a clear button appears which is not accessible with keyboard

**User Experience:**
If menu items and clear button will not be accessible with keyboard, then the users dependent on the keyboard will be unable to access the UI properly and may face trouble.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/keyboard

Have feedback to share on Bugs ? please tag bug as “A11yRCA” and add your feedback in the comment section

### Screenshots

The menu item appears after expanding the 'Add an action' button is not accessible with keyboard

https://github.com/microsoft/AdaptiveCards/assets/95913748/e434e30b-76a3-4ebd-87df-954b8c3fd559

### Card JSON

```JSON
NA
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue
Fixes #8825
Fixes #8826

# Description

Resolves some a11y fixes on the designer surface and the designer peers.

Updates include:
- Sending focus to the first element in a popup menu when it opens
- Allow the focus outline on peer buttons
- Add aria-lable, role, and tabIndex to designer peer buttons (drag & drop, remove, peer commands)
- Fix DOM tree ordering of dragPeer, removePeer, and commands
- Update aria-label for all designer peers to announce the type name and Empty state if it is a container element

# Sample Card

N/A

Changes can be tested with the default card and the empty card

# How Verified

Verified manually on the adaptive cards site.

### CODE REVIEW

**Review by jwoo-msft — APPROVED** [review]

**Review by natalie-aguinaldo — APPROVED** [review]

File: source/nodejs/adaptivecards-designer/src/peer-command.ts [hunk 1]
```diff
@@ -7,7 +7,10 @@ export class PeerCommand {
         let buttonElement = document.createElement("button");
         buttonElement.classList.add("acd-peerButton");
         buttonElement.type = "button";
+        buttonElement.setAttribute("role", "button");
         buttonElement.title = this.toolTip ? this.toolTip : this.name;
+        buttonElement.setAttribute("aria-label", this.toolTip ? this.toolTip : this.name);
```
Comment (paulcam206) [inline source/nodejs/adaptivecards-designer/src/peer-command.ts:12]: less a bug, but an opportunity to use a language feature:

```suggestion
        buttonElement.setAttribute("aria-label", this.toolTip ?? this.name);
```

**Review by paulcam206 — APPROVED** [review]

**Review by paulcam206 — APPROVED** [review]
