### PR TITLE
Fixes UI Issues

### LINKED ISSUE #1616: [ios]Hide scrollBar in button layout
simulator screen shot - iphone 8 - 2018-06-19 at 08 10 27

### PR DESCRIPTION
**Pull request by nesalang**
Resolves #1616  #1703 #1705

### CODE REVIEW

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm [hunk 1]
```diff
@@ -60,7 +60,13 @@ - (instancetype)initWithInputChoiceSet:(std::shared_ptr<AdaptiveCards::ChoiceSet
             }
             _defaultString = [titleArray componentsJoinedByString:@", "];
         } else {
-            _defaultString = @"";
+            NSString *firstChoice = nil;
+            if(!_choiceSetInput->GetChoices().empty()){
+                firstChoice = [NSString stringWithCString:(_choiceSetInput->GetChoices().begin()[0])->GetTitle().c_str() encoding:NSUTF8StringEncoding];
```
Comment (bviglietta) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm]: >.begin() [](start = 88, length = 8)

You can remove this call to begin().

Comment (nesalang) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSourceCompactStyle.mm]: Thanks

---
In reply to: [202846784](https://github.com/Microsoft/AdaptiveCards/pull/1709#discussion_r202846784) [](ancestors = 202846784)
