### PR TITLE
iOS new layout scheme

### LINKED ISSUE #3533: [iOS] [Layout] Incorrect ColumnSet layout when custom elements are present
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

We are a host for cards that we are authoring internally on our back-end.

# Version of SDK

iOS SDK v1.2.3

# Details

When we render adaptive cards that contain custom interface elements, the layout incorrectly ignores the "stretch" width setting on columns in the same column set, causing the layout to be incorrect.

Sample Card:
```
{
	"type": "AdaptiveCard",
	"version": "1.0",
	"body": [{
		"type": "TextBlock",
		"size": "medium",
		"weight": "bolder",
		"text": "Current Members",
		"spacing": "medium"
	}, {
		"type": "ColumnSet",
		"columns": [{
			"type": "Column",
			"width": "48px",
			"items": [{
				"type": "Image",
				"size": "medium",
				"style": "person",
				"url": "https://s3.amazonaws.com/spok-mgmt-web-static/directory/1-0-668-pr-1620-1/icons/profile.png",
				"horizontalAlignment": "center",
				"backgroundColor": "#f2f2f2"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "stretch",
			"items": [{
				"type": "TextBlock",
				"size": "medium",
				"weight": "bolder",
				"text": "John Doe",
				"wrap": true
			}, {
				"type": "TextBlock",
				"color": "light",
				"text": "Important Person",
				"wrap": true,
				"spacing": "none"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "auto",
			"items": [{
				"type": "ColumnSet",
				"columns": [{
					"type": "Column",
					"items": [{
						"type": "MessageActionBlock",
						"userId": "716aac77-4e5e-419c-9e2e-861ff80be83a",
						"userName": "John Doe",
						"contactType": "User",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}, {
					"type": "Column",
					"items": [{
						"type": "PhoneActionBlock",
						"phoneNumber": "(555) 555-5555",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}]
			}],
			"verticalContentAlignment": "center"
		}],
		"minHeight": "58px",
		"separator": true
	}, {
		"type": "ColumnSet",
		"columns": [{
			"type": "Column",
			"width": "48px",
			"items": [{
				"type": "Image",
				"size": "medium",
				"style": "person",
				"url": "https://s3.amazonaws.com/spok-mgmt-web-static/directory/1-0-668-pr-1620-1/icons/profile.png",
				"horizontalAlignment": "center",
				"backgroundColor": "#f2f2f2"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "stretch",
			"items": [{
				"type": "TextBlock",
				"size": "medium",
				"weight": "bolder",
				"text": "Ada Lovelace",
				"wrap": true
			}, {
				"type": "TextBlock",
				"color": "light",
				"text": "Important Person",
				"wrap": true,
				"spacing": "none"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "auto",
			"items": [{
				"type": "ColumnSet",
				"columns": [{
					"type": "Column",
					"items": [{
						"type": "MessageActionBlock",
						"userId": "aa311023-4c61-4ceb-9759-f80b0ec7dc29",
						"userName": "Ada Lovelace",
						"contactType": "User",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}]
			}],
			"verticalContentAlignment": "center"
		}],
		"minHeight": "58px",
		"separator": true
	}, {
		"type": "ColumnSet",
		"columns": [{
			"type": "Column",
			"width": "48px",
			"items": [{
				"type": "Image",
				"size": "medium",
				"style": "person",
				"url": "https://s3.amazonaws.com/spok-mgmt-web-static/directory/1-0-668-pr-1620-1/icons/profile.png",
				"horizontalAlignment": "center",
				"backgroundColor": "#f2f2f2"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "stretch",
			"items": [{
				"type": "TextBlock",
				"size": "medium",
				"weight": "bolder",
				"text": "Charles Babbage",
				"wrap": true
			}, {
				"type": "TextBlock",
				"color": "light",
				"text": "Important Person",
				"wrap": true,
				"spacing": "none"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "auto",
			"items": [{
				"type": "ColumnSet",
				"columns": [{
					"type": "Column",
					"items": [{
						"type": "MessageActionBlock",
						"userId": "00e18e62-8caa-41ba-8059-2d8b16e38027",
						"userName": "Charles Babbage",
						"contactType": "User",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}]
			}],
			"verticalContentAlignment": "center"
		}],
		"minHeight": "58px",
		"separator": true
	}, {
		"type": "ColumnSet",
		"columns": [{
			"type": "Column",
			"width": "48px",
			"items": [{
				"type": "Image",
				"size": "medium",
				"style": "person",
				"url": "https://s3.amazonaws.com/spok-mgmt-web-static/directory/1-0-668-pr-1620-1/icons/profile.png",
				"horizontalAlignment": "center",
				"backgroundColor": "#f2f2f2"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "stretch",
			"items": [{
				"type": "TextBlock",
				"size": "medium",
				"weight": "bolder",
				"text": "Steve Jobs",
				"wrap": true
			}, {
				"type": "TextBlock",
				"color": "light",
				"text": "Important Person",
				"wrap": true,
				"spacing": "none"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "auto",
			"items": [{
				"type": "ColumnSet",
				"columns": [{
					"type": "Column",
					"items": [{
						"type": "MessageActionBlock",
						"userId": "a6183196-d021-43d4-a03e-fb65d0b72667",
						"userName": "Steve Jobs",
						"contactType": "User",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}]
			}],
			"verticalContentAlignment": "center"
		}],
		"minHeight": "58px",
		"separator": true
	}, {
		"type": "ColumnSet",
		"columns": [{
			"type": "Column",
			"width": "48px",
			"items": [{
				"type": "Image",
				"size": "medium",
				"style": "person",
				"url": "https://s3.amazonaws.com/spok-mgmt-web-static/directory/1-0-668-pr-1620-1/icons/profile.png",
				"horizontalAlignment": "center",
				"backgroundColor": "#f2f2f2"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "stretch",
			"items": [{
				"type": "TextBlock",
				"size": "medium",
				"weight": "bolder",
				"text": "Grace Hopper",
				"wrap": true
			}, {
				"type": "TextBlock",
				"color": "light",
				"text": "Important Person",
				"wrap": true,
				"spacing": "none"
			}],
			"verticalContentAlignment": "center"
		}, {
			"type": "Column",
			"width": "auto",
			"items": [{
				"type": "ColumnSet",
				"columns": [{
					"type": "Column",
					"items": [{
						"type": "MessageActionBlock",
						"userId": "d50649e0-7925-4e79-9acb-fce36a7b2d17",
						"userName": "Grace Hopper",
						"contactType": "User",
						"size": "medium"
					}],
					"verticalContentAlignment": "center"
				}]
			}],
			"verticalContentAlignment": "center"
		}],
		"minHeight": "58px",
		"separator": true
	}]
}
```

On the Web and Android, the layout correctly stretches the center column (containing the names) so that the custom "MessageActionBlock" and "PhoneActionBlock" elements are pushed to the right edge of the row. On iOS, the layout fails to stretch, leaving the action buttons floating at incorrect positions.

ios-incorrect-layout

Also, here is the custom host config file we're using:

```
{
    "separator": {
        "lineColor": "#FFEDF1F7"
    },
    "supportsInteractivity": true,
    "imageSizes": {
        "small": 24,
        "medium": 40,
        "large": 80
    },
    "adaptiveCard": {
        "allowCustomStyle": false
    },
    "fontSizes": {
        "small": 11,
        "default": 13,
        "medium": 15,
        "large": 17,
        "extraLarge": 20
    },
    "fontWeights": {
        "lighter": 200,
        "default": 400,
        "bolder": 600
    },
    "containerStyles": {
        "default": {
            "foregroundColors": {
                "default": {
                    "default": "#ff222b45",
                    "subtle": "#ff222b45"
                },
                "light": {
                    "default": "#ff8f9bb3",
                    "subtle": "#ff8f9bb3"
                }
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by nesalang**
## Related Issue
fixed #3533, #3637, #3592 

## Description
* updated layoutview to take account for children's content size
* removed wrapper view from UITextView.
* updated layoutview to update children's content size dynamically with toggle visibility.
* fixed some of the issues of tailing views stretching when the main is hidden.

## How Verified
How you verified the fix, including one or all of the following: 
1. ran all cards and ensured that there is no regression.
2. tested with sample card provided to ensure the issues are fixed.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3687)

### CODE REVIEW

**Comment by paulcam206** [comment]
looks like iOS CI is failing here...

**Comment by shalinijoshi19** [comment]
@Aditya0603 FYI. This is the PR that we would like you to look at to help understand if this aids in getting away from needing to maintain your own custom fork of AC

**Comment by Aditya0603** [comment]
@shalinijoshi19 @nesalang looks like some problem with the adaptive cards Xcode project file in this branch.

**Comment by nesalang** [comment]
> @shalinijoshi19 @nesalang looks like some problem with the adaptive cards Xcode project file in this branch.

@Aditya0603 @shalinijoshi19 there were problem with project file. it's fixed now.

**Comment by nesalang** [comment]
> looks like iOS CI is failing here...

there was a problem with project file, it's fixed.

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.h [hunk 1]
```diff
@@ -37,6 +40,18 @@
                  priority:(unsigned int)priority
                  location:(ACRBleedDirection)location;
 
+- (UIView *)getLastArrangedSubview;
+
+- (CGFloat)getNextGreatWidth:(UIView *)view;
```
Comment (paulcam206) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.h]: I'm not sure what this function does just by its name... should we have comments or a more descriptive name?

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.h [hunk 2]
```diff
@@ -37,6 +40,20 @@
                  priority:(unsigned int)priority
                  location:(ACRBleedDirection)location;
 
+- (UIView *)getLastArrangedSubview;
+
+// return the largest width from the given subviews exluding the view
+- (CGFloat)getMaxWidthOfSubviewsAfterExluding:(UIView *)view;
+
+// return the largest height from the given subviews exluding the view
+- (CGFloat)getMaxHeightOfSubviewsAfterExluding:(UIView *)view;
```
Comment (bviglietta) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.h]: >Exluding [](start = 38, length = 8)

Excluding

**Comment by shalinijoshi19** [comment]
@nesalang, new POA is to commit this change to release/1.2 (and master), generate a private framework package for TEams mobile to consume and test wiht all the outbound v1.2.6 payload off of release/1.2. @Aditya0603 / @VikrantSingh01  FYI

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm [hunk 3]
```diff
@@ -52,6 +56,9 @@ - (instancetype)initWithFrame:(CGRect)frame attributes:(nullable NSDictionary<NS
 - (instancetype)initWithFrame:(CGRect)frame
 {
     self = [self initWithFrame:CGRectMake(0, 0, frame.size.width, frame.size.height) attributes:nil];
+    if (self) {
+        _hiddenSubviews = [[NSMutableSet alloc] init];
```
Comment (bviglietta) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm]: >_hiddenSubviews = [[NSMutableSet alloc] init]; [](start = 8, length = 46)

It's odd to put this initialization here but not in any of the other initializers. If this view is constructed via initWithCoder: or initWithFrame:attributes:, then `_hiddenSubviews` will never be constructed.

The usual pattern in Objective-C is to identify one initializer as the "designated initializer", and make sure that all initialization paths flow through it.

[http://www.timekl.com/blog/2014/12/09/objective-cs-designated-secret/](http://www.timekl.com/blog/2014/12/09/objective-cs-designated-secret/)

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm [hunk 4]
```diff
@@ -158,12 +198,53 @@ - (void)config:(nullable NSDictionary<NSString *, id> *)attributes
...
+// signals that the filling is done, and do the final visibility adjustment
+- (void)hideIfSubviewsAreAllHidden
+{
+    NSInteger count = [_hiddenSubviews count];
+    if (count and count == [_stackView.arrangedSubviews count]) {
+        self.hidden = YES;
+    }
+}
+
+- (void)observeValueForKeyPath:(NSString *)keyPath
```
Comment (bviglietta) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm]: >observeValueForKeyPath [](start = 8, length = 22)

It's possible to receive notifications that you didn't register for, usually because some superclass also registered for notifications on this object. Generally you should check whether this notification is for you (in this case, by checking whether `context == &kToggleVisibilityContext`) and, if not, forward the notification on up to [super observeValueForKeyPath:...].
