### PR TITLE
Fixed #5428

### LINKED ISSUE #5428: [iOS] Crash on iOS 13 when TextBlock includes an ampersand ("&")
# Platform

iOS

# Author or host

Host

# Version of SDK

2.4.6

# Details

Implementing a custom TextBlock renderer, it always crashes in ACRTextBlockRenderer.render() when running on iOS 13.

Steps to reproduce:
* Implement a custom TextBlock renderer (see below)
* Download iOS 13.6 SDK to Xcode if you don't already have it
* Run project in simulator using iOS 13.6

Result:
Crash. Backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BREAKPOINT (code=EXC_I386_BPT, subcode=0x0)
    frame #0: 0x000000011dd88466 JavaScriptCore`bmalloc::HeapConstants::HeapConstants(std::__1::lock_guard<bmalloc::Mutex> const&) + 326
    frame #1: 0x000000011dd87a8d JavaScriptCore`bmalloc::StaticPerProcess<bmalloc::HeapConstants>::getSlowCase() + 77
    frame #2: 0x000000011dd83dc8 JavaScriptCore`bmalloc::Heap::Heap(bmalloc::HeapKind, std::__1::lock_guard<bmalloc::Mutex>&) + 56
    frame #3: 0x000000011dd80865 JavaScriptCore`bmalloc::PerProcess<bmalloc::PerHeapKind<bmalloc::Heap> >::getSlowCase() + 181
    frame #4: 0x000000011dd810c5 JavaScriptCore`bmalloc::PerHeapKindBase<bmalloc::Cache>::PerHeapKindBase<>() + 37
    frame #5: 0x000000011dd80ae6 JavaScriptCore`bmalloc::PerThread<bmalloc::PerHeapKind<bmalloc::Cache> >::getSlowCase() + 102
    frame #6: 0x000000011dd80ba1 JavaScriptCore`bmalloc::Cache::allocateSlowCaseNullCache(bmalloc::HeapKind, unsigned long) + 129
    frame #7: 0x000000011dd31095 JavaScriptCore`WTF::StringImpl::createFromLiteral(char const*) + 37
    frame #8: 0x000000011dd77a12 JavaScriptCore`WTF::String::String(WTF::ASCIILiteral) + 18
    frame #9: 0x000000011f46a0a1 WebCore`WebCore::IOSApplication::isSpringBoard() + 49
    frame #10: 0x000000011f5ca4b7 WebCore`WebThreadEnable + 23
    frame #11: 0x000000011d188f8e WebKitLegacy`+[WebView(WebPrivate) enableWebThread] + 222
    frame #12: 0x000000011d1e1b16 WebKitLegacy`WebKitInitialize + 54
    frame #13: 0x0000000119481b6d UIKitCore`___UIApplicationLoadWebKit_block_invoke + 191
    frame #14: 0x0000000111bd3e8e libdispatch.dylib`_dispatch_client_callout + 8
    frame #15: 0x0000000111bd53db libdispatch.dylib`_dispatch_once_callout + 66
    frame #16: 0x0000000119481aac UIKitCore`_UIApplicationLoadWebKit + 35
    frame #17: 0x0000000111bd3e8e libdispatch.dylib`_dispatch_client_callout + 8
    frame #18: 0x0000000111bd53db libdispatch.dylib`_dispatch_once_callout + 66
    frame #19: 0x000000011cf65907 UIFoundation`__NSLoadWebKit + 93
    frame #20: 0x000000010449ef93 libobjc.A.dylib`CALLING_SOME_+initialize_METHOD + 17
    frame #21: 0x000000010449fdd1 libobjc.A.dylib`initializeNonMetaClass + 632
    frame #22: 0x00000001044a0d95 libobjc.A.dylib`initializeAndMaybeRelock(objc_class*, objc_object*, mutex_tt<false>&, bool) + 157
    frame #23: 0x00000001044ab5e1 libobjc.A.dylib`lookUpImpOrForward + 677
    frame #24: 0x000000010449ae99 libobjc.A.dylib`_objc_msgSend_uncached + 73
    frame #25: 0x000000011cef8cd7 UIFoundation`_NSReadAttributedStringFromURLOrData + 4941
    frame #26: 0x000000011cef7915 UIFoundation`-[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 98
    frame #27: 0x000000010c908074 AdaptiveCards`-[ACRTextBlockRenderer render:rootView:inputs:baseCardElement:hostConfig:](self=<unavailable>, _cmd=<unavailable>, viewGroup=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, acoElem=<unavailable>, acoConfig=0x00006000038ead00) at ACRTextBlockRenderer.mm:78:23 [opt]
  * frame #28: 0x0000000104103b8f PSFeedPrototyping`CustomTextBlockRenderer.render(viewGroup=0x00007ffa6870bb10, rootView=0x00007ffa6d02c9f0, inputs=0 elements, acoElem=0x0000600002d93080, acoConfig=0x00006000038ead00, self=0x0000600002fa3cb0) at CustomTextBlockRenderer.swift:19:56
    frame #29: 0x000000010410422d PSFeedPrototyping`@objc CustomTextBlockRenderer.render(_:rootView:inputs:baseCardElement:hostConfig:) at <compiler-generated>:0
    frame #30: 0x000000010c8b2e84 AdaptiveCards`+[ACRRenderer render:rootView:inputs:withCardElems:andHostConfig:](self=<unavailable>, _cmd=<unavailable>, view=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, elems=<unavailable>, config=0x00006000038ead00) at ACRRenderer.mm:199:34 [opt]
    frame #31: 0x000000010c91ecbe AdaptiveCards`-[ACRColumnRenderer render:rootView:inputs:baseCardElement:hostConfig:](self=0x0000600002fa3ae0, _cmd=<unavailable>, viewGroup=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, acoElem=<unavailable>, acoConfig=0x00006000038ead00) at ACRColumnRenderer.mm:66:5 [opt]
    frame #32: 0x000000010c86adcf AdaptiveCards`-[ACRColumnSetRenderer render:rootView:inputs:baseCardElement:hostConfig:](self=<unavailable>, _cmd=<unavailable>, viewGroup=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, acoElem=<unavailable>, acoConfig=0x00006000038ead00) at ACRColumnSetRenderer.mm:107:40 [opt]
    frame #33: 0x000000010c8b2e84 AdaptiveCards`+[ACRRenderer render:rootView:inputs:withCardElems:andHostConfig:](self=<unavailable>, _cmd=<unavailable>, view=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, elems=<unavailable>, config=0x00006000038ead00) at ACRRenderer.mm:199:34 [opt]
    frame #34: 0x000000010c8b3514 AdaptiveCards`-[ACRContainerRenderer render:rootView:inputs:baseCardElement:hostConfig:](self=<unavailable>, _cmd=<unavailable>, viewGroup=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, acoElem=<unavailable>, acoConfig=0x00006000038ead00) at ACRContainerRenderer.mm:57:5 [opt]
    frame #35: 0x000000010c8b2e84 AdaptiveCards`+[ACRRenderer render:rootView:inputs:withCardElems:andHostConfig:](self=<unavailable>, _cmd=<unavailable>, view=<unavailable>, rootView=<unavailable>, inputs=<unavailable>, elems=<unavailable>, config=0x00006000038ead00) at ACRRenderer.mm:199:34 [opt]
    frame #36: 0x000000010c8b2522 AdaptiveCards`+[ACRRenderer renderWithAdaptiveCards:inputs:context:containingView:hostconfig:](self=<unavailable>, _cmd=<unavailable>, adaptiveCard=std::__1::shared_ptr<AdaptiveCards::AdaptiveCard>::element_type @ 0x00006000014b5c18 strong=1 weak=1, inputs=<unavailable>, rootView=<unavailable>, containingView=<unavailable>, config=0x00006000038ead00) at ACRRenderer.mm:135:5 [opt]
    frame #37: 0x000000010c8fa754 AdaptiveCards`-[ACRView render](self=0x00007ffa6d02c9f0, _cmd=<unavailable>) at ACRView.mm:136:23 [opt]
    frame #38: 0x000000010c8fa4ef AdaptiveCards`-[ACRView init:hostconfig:widthConstraint:delegate:](self=0x00007ffa6d02c9f0, _cmd=<unavailable>, card=<unavailable>, config=<unavailable>, width=345, acrActionDelegate=<unavailable>) at ACRView.mm:113:9 [opt]
    frame #39: 0x000000010c8b1e34 AdaptiveCards`+[ACRRenderer render:config:widthConstraint:delegate:](self=<unavailable>, _cmd=<unavailable>, card=<unavailable>, config=<unavailable>, width=345, acrActionDelegate=<unavailable>) at ACRRenderer.mm:42:21 [opt]
    frame #40: 0x000000010c8b1f5d AdaptiveCards`+[ACRRenderer render:config:widthConstraint:](self=<unavailable>, _cmd=<unavailable>, card=<unavailable>, config=<unavailable>, width=<unavailable>) at ACRRenderer.mm:53:12 [opt]
    frame #41: 0x00000001040fd38a PSFeedPrototyping`ACCardLoader.renderCard(jsonStr="{\n  \"type\" : \"AdaptiveCard\",\n  \"$schema\" : \"http://adaptivecards.io/schemas/adaptive-card.json\",\n  \"version\" : \"1.3\",\n  \"my.backgroundColor\" : \"FFFFFFFF\",\n  \"my.cardHeight\": {\n      \"kind\": \"fixed\",\n      \"value\": 480\n  },\n  \"body\" : [\n      {\n          \"type\" : \"Container\",\n          \"backgroundImage\" : \"bundle://host/neon-bgnd.png\",\n          \"items\" : [\n              {\n                  \"type\" : \"ColumnSet\",\n                  \"height\" : \"stretch\",\n                  \"columns\" : [\n                      {\n                          \"type\" : \"Column\",\n                          \"width\" : \"12px\",\n                          \"comment\" : \"leading spacer\"\n                      },\n                      {\n                          \"type\" : \"Column\",\n                          \"items\" : [\n                              {\n                                  \"type\": \"PSSpacer\",\n                                  \"h\": 10\n                              },\n                              {\n                           "..., width=345, self=0x0000600002df8600) at ACCardLoader.swift:56:46
    frame #42: 0x000000010410bb1a PSFeedPrototyping`ViewController.tableView(tableView=0x00007ffa6c81b400, indexPath=<unavailable; try printing with "vo" or "po">, self=0x00007ffa6921a440) at ViewController.swift:54:47
    frame #43: 0x000000010410c915 PSFeedPrototyping`@objc ViewController.tableView(_:cellForRowAt:) at <compiler-generated>:0
    frame #44: 0x0000000119699e96 UIKitCore`-[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 867
    frame #45: 0x0000000119663522 UIKitCore`-[UITableView _updateVisibleCellsNow:] + 3010
    frame #46: 0x000000011968324e UIKitCore`-[UITableView layoutSubviews] + 194
    frame #47: 0x00000001199895f4 UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
    frame #48: 0x000000010e043260 QuartzCore`-[CALayer layoutSublayers] + 255
    frame #49: 0x000000010e0493eb QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 523
    frame #50: 0x000000010e054a8a QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 80
    frame #51: 0x000000010df9da7c QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double) + 324
    frame #52: 0x000000010dfd1467 QuartzCore`CA::Transaction::commit() + 649
    frame #53: 0x00000001194996c3 UIKitCore`__34-[UIApplication _firstCommitBlock]_block_invoke_2 + 81
    frame #54: 0x000000010d21fabc CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    frame #55: 0x000000010d21f1b3 CoreFoundation`__CFRunLoopDoBlocks + 195
    frame #56: 0x000000010d219fa3 CoreFoundation`__CFRunLoopRun + 995
    frame #57: 0x000000010d2198a4 CoreFoundation`CFRunLoopRunSpecific + 404
    frame #58: 0x00000001153f4bbe GraphicsServices`GSEventRunModal + 139
    frame #59: 0x0000000119481968 UIKitCore`UIApplicationMain + 1605
    frame #60: 0x000000010fd8192b libswiftUIKit.dylib`UIKit.UIApplicationMain(Swift.Int32, Swift.Optional<Swift.UnsafeMutablePointer<Swift.UnsafeMutablePointer<Swift.Int8>>>, Swift.Optional<Swift.String>, Swift.Optional<Swift.String>) -> Swift.Int32 + 155
    frame #61: 0x0000000104116e6a PSFeedPrototyping`static UIApplicationDelegate.main() at <compiler-generated>:0
    frame #62: 0x0000000104116dde PSFeedPrototyping`static AppDelegate.$main(self=PSFeedPrototyping.AppDelegate) at <compiler-generated>:0
    frame #63: 0x0000000104116eb9 PSFeedPrototyping`main at <compiler-generated>:0
    frame #64: 0x0000000111c5f1fd libdyld.dylib`start + 1
```

Custom TextBlock renderer looks like:

```
public class CustomTextBlockRenderer: ACRBaseCardElementRenderer {
    public override func render(
        _ viewGroup: (UIView & ACRIContentHoldingView)!,
        rootView: ACRView!,
        inputs: NSMutableArray!,
        baseCardElement acoElem: ACOBaseCardElement!,
        hostConfig acoConfig: ACOHostConfig!) -> UIView! {
        
        let view = ACRTextBlockRenderer.getInstance()?.render(   <----- crash here
            viewGroup,
            rootView: rootView,
            inputs: inputs,
            baseCardElement: acoElem,
            hostConfig: acoConfig)
        
        if let props = acoElem.additionalProperties {            
            let css = CSSCollection.cascadedCSS(jsonDict: props)

            if let label = view as? UILabel {
                label.stylizeWithCSS(css)
            } else if let textView = view as? UITextView {
                textView.stylizeWithCSS(css)
            } else {
                Logger.fileLog("*** Unknown text view type: \(view.debugDescription)")
            }
        }
        
        return view
    }
}
```

And registered like:

```
        acrRegistration.setBaseCardElementRenderer(CustomTextBlockRenderer(), cardElementType: .textBlock)
```

### PR DESCRIPTION
**Pull request by jwoo-msft**
## Related Issue
Fixed #5428 

## Description
We escape whenever `<`, `>`, `&` and `"`, and iOS renders the text as HTML. We don't have to render the text as HTML if we have such chars but MarkDown.
This change gives more flexibility to developers who develops on stacks that may run into issues when HTML text rendering is used.

## Sample Card
```json
{
  "type" : "AdaptiveCard",
  "$schema" : "http://adaptivecards.io/schemas/adaptive-card.json",
  "version" : "1.3",
  "body" : [
      {
          "type" : "TextBlock",
          "text" : "Foo & bar"
      }
  ]
}
```
## How Verified
Tested that HTML text rendering is not run with the sample card.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/5439)

### CODE REVIEW

File: source/shared/cpp/ObjectModel/MarkDownParser.cpp [hunk 1]
```diff
@@ -43,6 +43,11 @@ bool MarkDownParser::IsEscaped() const
     return m_isEscaped;
 }
 
+std::string MarkDownParser::GetText() const
+{
+    return m_text;
```
Comment (paulcam206) [inline source/shared/cpp/ObjectModel/MarkDownParser.cpp:48]: is it the case that this is un-modified text? if so, consider renaming to `MarkDownParser::GetRawText()`

**Review by paulcam206 — APPROVED** [review]

File: source/shared/cpp/ObjectModel/MarkDownParser.cpp (hunk 1 above)
Comment (jwoo-msft) [reply source/shared/cpp/ObjectModel/MarkDownParser.cpp:48]: Understood & thank you.
