### PR TITLE
Fixes AutoSize for Portrait Mode

### LINKED ISSUE #2846: Data URI Portrait Mode
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

The size of same DataURI image changes depending on which image style is used.

**InPerson**
image data uri inPerson

image data uri

### PR DESCRIPTION
**Pull request by nesalang**
Fixes #2846 

#2846 also applies to any portrait style. 

Auto size image grows up to its intrinsic size. When portrait style is applied, the image grows indefinitely. Fixed the image to grow up to its intrinsic content size.

How verified:
 
57166893-71a7ba00-6db0-11e9-84da-4d220604b738

No host config (default values) v1 2 Elements Image DataUri Style Person

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3318)

### CODE REVIEW

File: source/uwp/Renderer/lib/XamlBuilder.cpp [hunk 1]
```diff
@@ -2259,8 +2259,19 @@ namespace AdaptiveNamespace
 
         // Prevent an image from being stretched out if it is smaller than the
         // space allocated for it (when in auto mode).
-        RETURN_IF_FAILED(localElement->put_MaxHeight(min(maxHeight, pixelHeight)));
-        RETURN_IF_FAILED(localElement->put_MaxWidth(min(maxWidth, pixelWidth)));
+        ComPtr<IEllipse> localElementAsEllipse;
+        if(S_OK == localElement.As(&localElementAsEllipse))
```
Comment (almedina-ms) [inline source/uwp/Renderer/lib/XamlBuilder.cpp]: >S_OK == localElement.As(&localElementAsEllipse) [](start = 11, length = 47)

use SUCCEEDED()

File: source/uwp/Renderer/lib/XamlBuilder.cpp [hunk 2]
```diff
@@ -2306,11 +2317,16 @@ namespace AdaptiveNamespace
...
 
+            ComPtr<IFrameworkElement> ellipsAsFrameworkElement;
+            THROW_IF_FAILED(ellipse.As(&ellipsAsFrameworkElement));
+
             ComPtr<IImageSource> imageSource;
             THROW_IF_FAILED(brushAsImageBrush->get_ImageSource(&imageSource));
             ComPtr<IBitmapSource> imageSourceAsBitmap;
             THROW_IF_FAILED(imageSource.As(&imageSourceAsBitmap));
 
+            ComPtr<IInspectable> strongParentElement(parentElement);
```
Comment (almedina-ms) [inline source/uwp/Renderer/lib/XamlBuilder.cpp]: >ComPtr<IInspectable> strongParentElement(parentElement); [](start = 12, length = 56)

declare this inside the if as it is not used anywhere else
