### PR TITLE
Parse Context Update

### LINKED ISSUE #3509: [.NET][Unit Testing] FromJson throws exceptions when running unit tests in parallel
# Platform
.NET
botframework

# Version of SDK
NuGet version 1.2.3

# Details
I have multiple dialogs and multiple tests for each dialog in my chatbot project. I use cards in these dialogs, which are obtained from json files. When running all my tests, I get the following exception for most of the tests:

>   Message: 
>     System.InvalidOperationException : Stack empty.
>   Stack Trace: 
>     at Stack`1.ThrowForEmptyStack()
>     at Stack`1.Peek()
>     at ParseContext.PopElement()
>     at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
>     at WhereSelectEnumerableIterator`2.MoveNext()
>     at WhereSelectEnumerableIterator`2.ToList()
>     at Enumerable.ToList[TSource](IEnumerable`1 source)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>     at JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>     at JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
>     at JsonSerializerProxy.PopulateInternal(JsonReader reader, Object target)
>     at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at AdaptiveCardConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>     at JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>     at JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>     at AdaptiveCard.FromJson(String json)

and one test returns the following error:

>   Message: 
>     System.NullReferenceException : Object reference not set to an instance of an object.
>   Stack Trace: 
>     at ParseContext.PopElement()
>   at AdaptiveTypedElementConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>     at JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>     at JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>     at JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
>     ...

When running the unit tests one by one, all of the pass.
It looks like AdaptiveCards.FromJson cannot handle multiple simultaneous calls.

### LINKED ISSUE #3541: [.NET WPF] Possible race condition in ParseContext.cs; causing 100% CPU usage in Azure Bot Service
# Platform

.NET WPF

### PR DESCRIPTION
**Pull request by nesalang**
## Related Issue
fixes #3509, fixes #3541 

## Description
ParseContext was a static class, and it caused synchronization issue during parsing in multi-threaded environments.

- this changes include:
1. Made ParseContext non static class
2. Added an instance of ParseContext to WarningLoggingContractResolver.
- so client's custom Json contract resolver may not work.
- we already don't allow custom Json contract resolver if FromJson() API is used
3. Fixed the issue where internalIds are not being set for elements
4. Added concurrency unit test for parsing

## How Verified
1. Concurrency unit tests were added and verified it.
2. All existing unit tests were passed
3. Run all of the fallback json tests cards and ran some of the relevant cards such as showcard

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3548)

### CODE REVIEW

File: source/dotnet/Library/AdaptiveCards/AdaptiveFallbackConverter.cs [hunk 1]
```diff
@@ -2,10 +2,11 @@
 using Newtonsoft.Json.Linq;
 using System;
 using System.Collections.Generic;
+using System.Runtime.CompilerServices;
```
Comment (paulcam206) [inline source/dotnet/Library/AdaptiveCards/AdaptiveFallbackConverter.cs]: is this needed?

File: source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs [hunk 2]
```diff
@@ -62,16 +62,21 @@ public override object ReadJson(JsonReader reader, Type objectType, object exist
...
-
                 ValidateJsonVersion(ref jObject);
 
                 if (new AdaptiveSchemaVersion(jObject.Value<string>("version")) > AdaptiveCard.KnownSchemaVersion)
                 {
                     return MakeFallbackTextCard(jObject);
                 }
             }
+
+            /// this is needed when client calls Deserailizer method, we need this contract resolver,
```
Comment (paulcam206) [inline source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs]: >Deserailizer [](start = 49, length = 12)

nit: typo :)

File: source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs [hunk 3]
```diff
@@ -1244,6 +1244,152 @@ public void TestParsingRichTextBlockWithInvalidInlineType()
...
+                        ""type"": ""Action.Submit"",
+                        ""title"": ""OK""
+                    }
+                ]
+            }
+        }
+    ]
+}";
+            List<Task> tasks = new List<Task>();
+            for (var i = 0; i < 10; i++)
```
[the remark this answers is not in the document]
Comment (nesalang) [reply source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs]: yes, this was sufficient to trigger errors.

---
In reply to: [340736088](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r340736088) [](ancestors = 340736088)

File: source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs (hunk 2 above)
Comment (nesalang) [reply source/dotnet/Library/AdaptiveCards/AdaptiveCardConverter.cs]: thanks!

---
In reply to: [340735553](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r340735553) [](ancestors = 340735553)

File: source/dotnet/Library/AdaptiveCards/AdaptiveFallbackConverter.cs (hunk 1 above)
Comment (nesalang) [reply source/dotnet/Library/AdaptiveCards/AdaptiveFallbackConverter.cs]: thanks

---
In reply to: [340735289](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r340735289) [](ancestors = 340735289)

File: source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+using Newtonsoft.Json;
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
+
+namespace AdaptiveCards
+{
+    public abstract class AdaptiveTypedBaseElementConverter : JsonConverter
```
Comment (shalinijoshi19) [inline source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs]: Late but adding comments anyways; Good to have some class comments explainng why this wasnt needed for eg. Also do you need System.Threading.Tasks here?

File: source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs [hunk 5]
```diff
@@ -0,0 +1,24 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+using Newtonsoft.Json;
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Text;
+using System.Threading.Tasks;
```
Comment (shalinijoshi19) [inline source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs]: Nit: Should be able to clean up the using's here to remove ones not being used in the file

File: source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs [hunk 6]
```diff
@@ -0,0 +1,24 @@
...
+
+namespace AdaptiveCards
+{
+    public abstract class AdaptiveTypedBaseElementConverter : JsonConverter
+    {
+        protected ParseContext parseContext;
+        public ParseContext ParseContext
```
Comment (shalinijoshi19) [inline source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs]: Curious: Wouldnt automatic properties work here?Also why is the local member (parseContext) declared as protected? Additionally why is ParseContext - the property a public property vs protected?

File: source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs (hunk 5 above)
Comment (nesalang) [reply source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs]: thanks

---
In reply to: [341278562](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r341278562) [](ancestors = 341278562)

File: source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs (hunk 4 above)
Comment (nesalang) [reply source/dotnet/Library/AdaptiveCards/AdaptiveTypedBaseElementConverter.cs]: sure
and good catch! will remove it

---
In reply to: [341278327](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r341278327) [](ancestors = 341278327)

File: source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs [hunk 7]
```diff
@@ -1245,5 +1245,155 @@ public void TestParsingRichTextBlockWithInvalidInlineType()
 
             StringAssert.Contains(ex.Message, "Property 'type' must be 'TextRun'");
         }
```
Comment (shalinijoshi19) [inline source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs]: nit: newline here to break between functions

Comment (nesalang) [reply source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs]: thanks

---
In reply to: [341284053](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r341284053) [](ancestors = 341284053)

File: source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs [hunk 8]
```diff
@@ -1245,5 +1245,155 @@ public void TestParsingRichTextBlockWithInvalidInlineType()
...
+
+            try
+            {
+                Task.WaitAll(tasks.ToArray());
+            }
+            catch
+            {
+                // it's perfectly fine card. if there is exception, it is due to concurreny
+                // as it's the only variable.
+                Assert.Fail();
```
Comment (shalinijoshi19) [inline source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs]: Nit: Include a message here in case the assertion fails to aid debugging a bit by adding some failure context

Comment (nesalang) [reply source/dotnet/Test/AdaptiveCards.Test/AdaptiveCardApiTests.cs]: good catch; it wasn't carried over from the stopgap since they were worked at in parrarrell.


---
In reply to: [341284485](https://github.com/microsoft/AdaptiveCards/pull/3548#discussion_r341284485) [](ancestors = 341284485)
