### PR TITLE
[UWP] Apply stretch property to auto sized person elements

### LINKED ISSUE #2548: [UWP] Regression: Image with explicit size and person style clipped rather than stretched
In UWP (current master), an image with explicit size and style:person ends up clipped rather than stretched (see `Tests\Image.Explicit.Size.json`):

image

### PR DESCRIPTION
**Pull request by paulcam206**
Fixes #2548 

The original regression occurred in 6ffc99b as a fix for #2400 (PR'd in #2520). Basically, in non-explicitly-sized-cases, we were failing to set the `stretch` property properly.

Verified with AdaptiveCardTestApp and with the original bugged card in the Visualizer. I will update this PR with a sample card covering the original bugged scenario.

### CODE REVIEW

**Comment by nesalang** [comment]
>                 // We don't want to set a max height on the person ellipse as ellipses do not understand preserving

this comment isn't true. person image style isn't always 1:1 aspect raito, this is true in this else case because the size is set to small/medium/large, and they are squares.

---
Refers to: source/uwp/Renderer/lib/XamlBuilder.cpp:2569 in e7ed767. [](commit_id = e7ed7677e813e8817332c6776e360a535196ccc3, deletion_comment = False)

File: source/uwp/Renderer/lib/XamlBuilder.cpp [hunk 1]
```diff
@@ -2417,11 +2417,20 @@ namespace AdaptiveNamespace
...
 
-            // Set the stretch for the ellipse - this is different to the stretch used for the image brush above.
-            // This will force the ellipse to conform to fit within the confines of its parent.
-            Stretch ellipseStretch = Stretch::Stretch_UniformToFill;
-            RETURN_IF_FAILED(ellipseAsShape->put_Stretch(ellipseStretch));
-            RETURN_IF_FAILED(backgroundEllipseAsShape->put_Stretch(ellipseStretch));
+            if (size == ABI::AdaptiveNamespace::ImageSize::None || size == ABI::AdaptiveNamespace::ImageSize::Stretch ||
+                size == ABI::AdaptiveNamespace::ImageSize::Auto || hasExplicitMeasurements)
+            {
+                THROW_IF_FAILED(ellipseAsShape->put_Stretch(imageStretch));
```
Comment (paulcam206) [inline source/uwp/Renderer/lib/XamlBuilder.cpp]: >THROW_IF_FAILED [](start = 16, length = 15)

should be `RETURN_IF_FAILED`
