### PR TITLE
Eschavez/layout fixes

### LINKED ISSUE #1085: HorizontalFlowLayout - Each item in the layout takes up the entire width of the container
Used by ImageSet and Actions to show items in a row side-by-side. Currently each item is taking up an entire row

### PR DESCRIPTION
**Pull request by eschavez**
Closes #1085, #1106, #1107, #1109

### CODE REVIEW

File: source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java [hunk 1]
```diff
@@ -6,9 +6,6 @@
 import android.widget.RelativeLayout;
 
 /**
- * Credit: Adil Hussain
```
Comment (nesalang) [inline source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java]: is removing this comments O.K?

File: source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/readonly/ColumnRenderer.java [hunk 2]
```diff
@@ -58,8 +58,12 @@ public View render(
     {
         LinearLayout.LayoutParams layoutParams;
         BaseCardElementVector baseCardElementVector = column.GetItems();
+        setSpacingAndSeparator(context, viewGroup, column.GetSpacing(), column.GetSeparator(), hostConfig, false);
+
         View returnedView = CardRendererRegistration.getInstance().render(context, fragmentManager, null, column, baseCardElementVector, inputActionHandlerList, hostConfig);
         String columnSize = column.GetWidth().toLowerCase(Locale.getDefault());
+
+
         if (TextUtils.isEmpty(columnSize) || columnSize.equals(g_columnSizeAuto))
```
Comment (nesalang) [inline source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/readonly/ColumnRenderer.java]: nit: two new lines.

File: source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java [hunk 3]
```diff
@@ -50,9 +47,9 @@ public HorizontalFlowLayout(Context context, AttributeSet attrs, int defStyle) {
 //     *
 //     * TODO: uncomment this constructor once the minimum API level of this project is changed to 21 (Lollipop).
 //     */
-    public HorizontalFlowLayout(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
-        super(context, attrs, defStyleAttr, defStyleRes);
-    }
+//    public HorizontalFlowLayout(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
```
Comment (nesalang) [inline source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java]: testing done?

Comment (eschavez) [reply source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java]: Since we will be going to min-version 19, this will remain commented out.

File: source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java (hunk 1 above)
Comment (eschavez) [reply source/android/adaptivecards/src/main/java/com/microsoft/adaptivecards/renderer/layout/HorizontalFlowLayout.java]: Need to give credit. Keeping as is.
