### PR TITLE
[UWP] Fix visibility issues with Columns and Separators

### LINKED ISSUE #2586: [UWP][1.2] isVisible on column doesn't work
# Platform

* UWP

# Version of SDK

1.2.0-beta

# Issue

`isVisible` doesn't seem to work on columns in UWP. Similarly, trying to toggle the visibility of a Column doesn't work.

For example, see below... the column renders despite isVisible being set to false.

```json
                {
                    "type": "Column",
                    "spacing": "small",
                    "verticalContentAlignment": "center",
                    "id": "chevronUp2",
                    "isVisible": false,
```

Test payload is on https://messagecardplayground.azurewebsites.net/ (select the Zoho sample)

**Expected**
 
image

**Actual**: Both buttons appear since column visibility isn't respected
 
image

### LINKED ISSUE #2608: [UWP] Ensure ToggleVisibility interacts with separators correctly
**Automatically generated task. Any updates to the title and body will be overwritten. Do NOT modify the labels.**

UWP fix of #2600

### PR DESCRIPTION
**Pull request by RebeccaAnne**
Updated the UWP code to address the scenarios of columns that have their visibility set or toggled, and separators that should have their visibility toggled along with the elements they belong to.

Fixes #2586 
Fixes #2608 

How verified: Manual verification using the existing Toggle card, and ran the UWP test app.

### CODE REVIEW

File: source/uwp/Renderer/lib/ElementTagContent.cpp [hunk 1]
```diff
@@ -0,0 +1,41 @@
+#include "pch.h"
```
Comment (paulcam206) [inline source/uwp/Renderer/lib/ElementTagContent.cpp]: missing copyright banner :)

File: source/uwp/Renderer/lib/XamlBuilder.cpp [hunk 2]
```diff
@@ -1284,6 +1350,57 @@ namespace AdaptiveNamespace
...
     }
 
+    HRESULT HandleColumnWidth(_In_ IAdaptiveColumn* column, boolean isVisible, _In_ IColumnDefinition* columnDefinition)
+    {
+        HString adaptiveColumnWidth;
+        RETURN_IF_FAILED(column->get_Width(adaptiveColumnWidth.GetAddressOf()));
+
+        INT32 isStretchResult;
+        RETURN_IF_FAILED(WindowsCompareStringOrdinal(adaptiveColumnWidth.Get(), HStringReference(L"stretch").Get(), &isStretchResult));
+        boolean isStretch = (isStretchResult == 0);
```
Comment (paulcam206) [inline source/uwp/Renderer/lib/XamlBuilder.cpp]: could be const (and below as appropriate)
