### PR TITLE
[a11y] Add aria-required for inputs

### LINKED ISSUE #8931: {Linked:Bug50553332}[Adaptive Cards > Designer] - All Required fields (shown with a red Asterix) should be called out as required in narrator
### Target Platforms

Other

### SDK Version

1.6

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
URL: https://adaptivecards.io/designer/
OS Version: 24H2 (OS Build 26217.5000)
Browser Version: Version 127.0.2610.3 (Official build) dev (64-bit)
Screen Reader: Narrator

**Pre-Requisite:**
Run the below attached JSON file under 'Copy Card Payload editor.'

**Repro Steps:**
1. Open the above URL on the EDGE Dev browser.
2. Run the Json file.
3. Navigate to the Preview mode and press enter key to activate it.
4. Press tab key, navigate to all required fields, and observe the issue.

**Actual Result:**
Screen Reader does not announce required information while navigating on the edit field or combo box.

**Expected Result:**
Screen Reader should announce the required information with the edit and combo box.

**User Impact:**
It will impact the screen reader user as they will not be able to know which field is required due to this there might be a chance that they may skip the field.

**WCAG Reference Link:**
https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

Have feedback to share on Bugs ? please tag bug as “A11yRCA” and add your feedback in the comment section

### Screenshots

https://github.com/microsoft/AdaptiveCards/assets/95913748/d08ae7ef-184e-4166-be54-32f0f98c2ba9

Screen Reader is not announcing required information

### Card JSON

```JSON
{ "type": "AdaptiveCard", "$schema": "http://adaptivecards.io/schemas/adaptive-card.json", "version": "1.5", "body": [ { "type": "ColumnSet", "spacing": "large", "columns": [ { "type": "Column", "width": "auto", "items": [ { "type": "Input.Text", "id": "NewEnvironmentName", "label": "${EnterNewEnvironmentTextBoxLabel}", "maxLength": 100, "isRequired": true, "errorMessage": "${DevBoxTextBoxErrorMessage}", "regex": "${DevBoxNameRegex}", "spacing": "large", "value": "${TextBoxText}" } ] } ] }, { "type": "ColumnSet", "spacing": "large", "columns": [ { "type": "Column", "width": "stretch", "items": [ { "type": "Input.ChoiceSet", "id": "ProjectsComboBox", "label": "${ProjectComboBoxLabel}", "devHomeChildChoiceSetId": "PoolsComboBox", "devHomeSelectionChangedDataForChildChoiceSet": "${SelectionChangedDataForChildChoiceSet}", "devHomeRefreshChildChoiceSetOnSelectionChanged": true, "isRequired": true, "errorMessage": "${DevBoxProjectComboBoxErrorMessage}", "style": "compact", "value": "${SelectedProjectIndex}", "choices": [ { "$data": "${ProjectList}", "title": "${title}", "value": "${value}" } ] } ] } ] }, { "type": "ColumnSet", "spacing": "large", "columns": [ { "type": "Column", "width": "stretch", "items": [ { "type": "Input.ChoiceSet", "id": "PoolsComboBox", "devHomeParentChoiceSetId": "ProjectsComboBox", "label": "${DevBoxPoolComboBoxLabel}", "isRequired": true, "errorMessage": "${DevBoxPoolsComboBoxErrorMessage}", "placeholder": "${DevBoxPoolsPlaceHolder}", "style": "compact", "value": "${SelectedPoolIndex}", "devHomeChoicesData": [ { "$data": "${PoolsList}", "title": "${title}", "subtitle": "${subtitle}", "value": "${value}" } ] } ] } ] }, { "type": "ActionSet", "id": "DevHomeTopLevelActionSet", "actions": [ { "id": "DevHomeMachineConfigurationNextButton", "type": "Action.Submit", "title": "${PrimaryButtonLabelForCreationFlow}" }, { "id": "DevHomeMachineConfigurationPreviousButton", "type": "Action.Submit", "title": "${SecondaryButtonLabelForCreationFlow}" } ] } ] }
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue
Fixes #8931

# Description

Add `aria-required: true` to Inputs that are required.

# Sample Card

See attached issues.

# How Verified

Verified with CI site.

### CODE REVIEW

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 1]
```diff
@@ -4121,10 +4125,6 @@ export class ToggleInput extends Input {
             this._checkboxInputElement.setAttribute("aria-label", this.title);
         }
 
-        if (this.isRequired) {
```
Comment (jwoo-msft) [inline source/nodejs/adaptivecards/src/card-elements.ts:4124]: why do you remove this?

**Review by jwoo-msft — APPROVED** [review]

File: source/nodejs/adaptivecards/src/card-elements.ts (hunk 1 above)
Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts:4124]: I added `aria-required` the parent input renderer. This assignment should now be redundant.

I need to verify this with the CI site.

Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts]: Updated

**Review by jwoo-msft — APPROVED** [review]
