### PR TITLE
[.NET Templating] Resolve commas added in wrong place

### LINKED ISSUE #6680: [Bug] [Templating] [dot Net] Get extra comma when binding data to an AdaptiveCardTemplate
# Platform

What platform is your issue or question related to? (Delete other platforms).

* .NET 5.0

# Author or host

Are you an author (like sending something to Outlook), or a host that is rendering your own cards? If host, please specify the corresponding host (app) name.

* Author

If you're an author, who are you sending cards to?

* Microsoft Teams

# Version of SDK

What version are you using? Ex: NuGet 1.0.2, or latest main, etc...

* Dot Net NuGet AdaptiveCards.Templating 1.2.2

# Issue

When I call `AdaptiveCardTemplate.Expand()` to bind data to an AdaptiveCardTemplate, the returned string contains some extra commas, which produces ill-formed json string.

# Repro Steps
## Code
```C#
var cardTemplate = new AdaptiveCardTemplate(templateJsonString);
string expand = cardTemplate.Expand(dataJsonString);
Console.WriteLine($"Contain ,,: {expand.Contains(",,")}");
Console.WriteLine($"Contain ,]: {expand.Contains(",]")}");
```
### Sample Template
```json
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
      {
        "type": "ColumnSet",
        "$data": "${foo}",
        "$when": "${$index==0}"
      },
      {
        "type": "Container",
        "$data": "${foo}",
        "$when": "${$index>0}"
      }
    ]
}
```
### Sample Data
```json
{
	"foo": [{}, {}]
}
```
### Expanded String
```json
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.3","body":[{"type":"ColumnSet"},,{"type":"Container"}]}
```

### Sample Template
```json
{
	"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
	"type": "AdaptiveCard",
	"version": "1.3",
	"body": [{
		"type": "Container",
		"items": [{
			"type": "Container",
			"$when": "${bar==1}"
		}, {
			"type": "ColumnSet",
			"$when": "${bar==2}"
		}],
		"$data": "${foo}"
	}]
}
```
### Sample Data
```json
{
	"foo": [{
		"bar": 1
	}]
}
```
### Expanded String
```json
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.3","body":[{"type":"Container","items":[{"type":"Container"},]}]}
```
## Expected behavior
The expanded string should contain no extra commas. Any ill-formed json token, like `,,` or `,]` should not appear.
```json
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.3","body":[{"type":"ColumnSet"},{"type":"Container"}]}
```
```json
{"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","type":"AdaptiveCard","version":"1.3","body":[{"type":"Container","items":[{"type":"Container"}]}]}
```

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue

Fixes #6680 

# Description

Commas were sometimes being added unnecessarily which resulted in invalid JSON. I updated `TemplateVisitor` to only add commas if there is an object prior and another object is about to be added.

# Sample Card

Card:
```
{
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "type": "AdaptiveCard",
    "version": "1.3",
    "body": [
      {
        "type": "ColumnSet",
        "$data": "${foo}",
        "$when": "${$index==0}"
      },
      {
        "type": "Container",
        "$data": "${foo}",
        "$when": "${$index>0}"
      }
    ]
}
```

Data:
```
{
	"foo": [{}, {}]
}
```

# How Verified

Verified manually and with the added unit tests.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/7225)

### CODE REVIEW

File: source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs [hunk 1]
```diff
@@ -508,11 +509,14 @@ public override AdaptiveCardsTemplateResult VisitObj([NotNull] AdaptiveCardsTemp
 
                 if (whenEvaluationResult != AdaptiveCardsTemplateResult.EvaluationResult.EvaluatedToFalse)
                 {
-                    if (iObj != repeatsCounts - 1)
+                    if (isObjAdded)
                     {
-                        result.Append(jsonPairDelimieter);
+                        // add a delimiter, e.g ',' before appending
+                        // another object after first object is added
+                        combinedResult.Append(jsonPairDelimiter);
```
Comment (beervoley) [inline source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs:516]: why `combinedResult` here?:) `result` is being added to the `combinedResult` anyway:)

Comment (anna-dingler) [reply source/dotnet/Library/AdaptiveCards.Templating/AdaptiveCardsTemplateVisitor.cs:516]: Appending to `result` makes the delimiter appear after the `result`, but we need the delimiter to be before the `result`
