### PR TITLE
[Website] Custom table generator to include aria-label

### LINKED ISSUE #8360: {Freeway-Bug}[Adaptive Cards - Text Block] - Screen Reader is not conveying the 'Name' of table under 'Text Block'.
### Target Platforms

Other

### SDK Version

1.5

### Application Name

Adaptive Cards

### Problem Description

**Test Environment:**
OS: Version 22H2 (OS Build 25300.1000)
URL: https://adaptivecards.io/explorer/TextBlock.html
Browser: Edge Dev Version 111.0.1661.36 (Official build) dev (64-bit)
Screen Reader: Narrator

**Repro Steps:**
1. Open the above URL in the edge dev browser.
2. Navigate to the 'Text Block' under 'Card Elements' and press enter key to select it.
3. Navigate to the Table present under the Text block and observe the issue.

**Actual Result:**
While navigating to the table present under 'Text block' using 'T' key, screen reader is not conveying the name of the table. It is announcing only description of the table.

**Expected Result:**
While navigating to the table using 'T' key, screen reader should convey the name of the Table and it should announce as 'Text Block' table then it should announce the description.

**Note:**
This issue is repro throughout the application for the tables.

**Observation:**
Same issue repro through the NVDA Screen Reader.

**User Impact:**
It will impact the screen reader user if the name of the table is not defined as they will face difficulty understanding if there are multiple tables on the page with same description.

**WCAG Reference:**
https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

"Have feedback to share on Bugs ? Please help fill [Trusted Tester Bug Feedback (office.com)](https://nam06.safelinks.protection.outlook.com/?url=https://forms.office.com/pages/responsepage.aspx?id%3Dv4j5cvGGr0GRqy180BHbR5dUqGQgJ9lItv-jqY8F09lURVdYTENIRkY2UzlCR0NKV1E2VUE5OVpDVy4u&data=04%7c01%7cv-apoorva%40microsoft.com%7c551850210d444be9b28308d9691e3dde%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637656400998658942%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c1000&sdata=l6w0SvVcMSvyGnJ6%2B6uSSgd3braF2dZ7/AdBrqqzIR8%3D&reserved=0) “,

### Screenshots

https://user-images.githubusercontent.com/95913748/224633462-bfcca258-4af3-47b9-b393-afb4707aae7b.mp4

MAS4 1 2-Screen Reader is not conveying the 'Name' of table under 'Text Block'

### Card JSON

```JSON
NA
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue

Fixes #8360

# Description

The markdown to html generator does not include narrator support for the table title. To fix this, we need to include a custom table renderer.

Since markdown does not contain a title element, I added the following steps to detect the table title.
- Within the first header cell, append the appropriate title wrapped in braces
- When we generate the html, parse for the title within the braces
- Remove the title from the header html before returning it

The table title is then used as the `aria-label` and is announced properly by Narrator

# Sample Card

N/A - see generated website

# How Verified

Verified manually on the AC site.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/8622)

### CODE REVIEW

File: source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/filter-table.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    // <tr>
+    // <th>{ActionSet Inherited properties}Property</th>
+    // <th>Type</th>
+    // <th>Required</th>
+    // <th>Description</th>
+    // <th>Version</th>
+    // </tr>
+
+    // Index of the end of the title
+    var closingIndex = header.indexOf("}");
```
Comment (anna-dingler) [inline source/nodejs/adaptivecards-site/themes/adaptivecards/scripts/filter-table.js:20]: We might want to handle more edge cases here? I'm not sure if other areas of our website will be impacted here

File: source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts [hunk 2]
```diff
@@ -164,9 +164,20 @@ function createTable(formattedProperties: any[]) {
...
 		headerRow.push(__(propName));
 	}
+
+	// Used for custom table rendering.
+	// We append the table title (wrapped in braces) to the first cell in the header,
+	// and the table renderer will use this value for aria-label.
+	// It is then removed from the header.
+	var firstValue = headerRow[0];
+	if (firstValue) {
+		headerRow[0] = `{${title}}` + firstValue;
```
Comment (paulcam206) [inline source/nodejs/ac-typed-schema/src/markdown/generate-markdown.ts:178]: Like you, I'm not a big fan of this approach... However, to do this in a more structured way may require a lot of work (that would itself likely be pretty flaky).

That said, we should probably wrap the title more cleanly... 
  - Consider using `{{` and `}}` as your delimiters
  - Perhaps even use `<!-- TableTitle: "Title goes here" -->`?
  - When parsing the title out in the renderer, instead of assuming that the title exists and begins at index `10`, look for the delimiters and pull them out that way -- this helps ensure that this functionality is robust to changes in `marked` output

**Review by paulcam206 — CHANGES_REQUESTED** [review]

**Review by paulcam206 — APPROVED** [review]
:shipit:
