### PR TITLE
Jwoo/ios a11y date picker

### LINKED ISSUE #6281: [Rendering] Bug Title Here
### Target Platforms

iOS

### SDK Version

Main

### Application Name

Visualizer

### Problem Description

[29527794](https://microsoft.visualstudio.com/OS/_workitems/edit/29527794)

### Screenshots

_No response_

### Card JSON

```JSON
kklj
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### LINKED ISSUE #6284: [Accessibility] Voiceover convey the incorrect position of the 'Snooze For' dropdown menu items under the 'CalendarReminder JSON' screen.
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33751792](https://microsoft.visualstudio.com/OS/_workitems/edit/33751792)

Voiceover should convey the correct correct position of the menu items. It should announce as '5 minutes 1 of 3 , 15 minutes 2 of 3'

If voiceover is not reading the position of list items in “Snooze For” dropdown on “CalendarReminder” page then voiceover user will not be able to find out the position of list items and will be confused and face difficulties to navigate in the list on screen.

### Screenshots

_No response_

### Card JSON

```JSON
https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/CalendarReminder.json
```

### Sample Code Language

_No response_

### Sample Code

_No response_

### LINKED ISSUE #6287: [Accessibility] Voice over does not convey the name of the 'DatePicker' button under 'ActivityUpdate.JSON' screen.
### Target Platforms

iOS

### SDK Version

App Version: Version 1.0 (2.3.1-beta.20210603.1)

### Application Name

Visualizer

### Problem Description

[33753620](https://microsoft.visualstudio.com/OS/_workitems/edit/33753620)

Voice Over does not convey the name of the 'Date Picker' button, Currently VO does announce as 'Button' only.

### Screenshots

_No response_

### Card JSON

[ActivityUpdate.json](https://github.com/microsoft/AdaptiveCards/blob/main/samples/v1.0/Scenarios/ActivityUpdate.json)

### Sample Code Language

_No response_

### Sample Code

_No response_

### LINKED ISSUE #7020: [Adaptive Card iOS - ChoiceSet.UnclippedText]: Voice over does convey the incorrect role as 'Button' for the radio buttons.
https://microsoft.visualstudio.com/OS/_workitems/edit/37842970

### PR DESCRIPTION
**Pull request by jwoo-msft**
# Related Issue
Fixed #7020, Fixed #6281, Fixed #6284, Fixed #6287

# Description
updated a11y labels and hints

# How Verified

verified manually using sample cards.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/7555)

### CODE REVIEW

**Review by almedina-ms — APPROVED** [review]

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputDateRenderer.mm [hunk 1]
```diff
@@ -39,6 +39,7 @@ - (UIView *)render:(UIView<ACRIContentHoldingView> *)viewGroup
 
     ACRInputLabelView *inputLabelView = [[ACRInputLabelView alloc] initInputLabelView:rootView acoConfig:acoConfig adptiveInputElement:dateInput inputView:dateField accessibilityItem:dateField.inputView viewGroup:viewGroup dataSource:nil];
     dateField.accessibilityTraits = UIAccessibilityTraitButton | UIAccessibilityTraitStaticText;
+    dateField.accessibilityHint = NSLocalizedString(@"opens the date picker", nil);
```
Comment (almedina-ms) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputDateRenderer.mm:42]: at some point localization is going to come for us D:

Comment (jwoo-msft) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputDateRenderer.mm:42]: it will; i filed for the exception for that reasons; but we never got around the issue while we were in the grace period.
