### PR TITLE
Changed Textview to Update Its Text Color Correctly According to Theme

### LINKED ISSUE #4215: [iOS][InputFiedl - Keyboard] [Japanese keyboard is not working properly with ACRTextField input field]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Team iOS

# Version of SDK

1.2.7

# Details

Default Japanese Keyboard font changes to English font inside ACRTextField input fields. Works fine with ACRTextView input fields.

Repro steps:
- Add Japanese keyboard as one of your keyboards
- Tap on multi line input field and try changing language to Japanese -> This works fine
- Tap on single line input field and try changing language to Japanese -> Notice a different Japanese keyboard pops up this time with default English script.
PFA the screenshots of the two different keyboards.

|Expected|Actual|
|:-:|:-:|
|drawing | drawing|

### LINKED ISSUE #4216: [iOS][Font color - Input Fields] [Font color in ACRTextView gets overwritten]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* iOS

# Author or host

Host - Teams iOS

# Version of SDK

1.2.7

# Details
Issues:
- ACRTextView overwrites the defined font color in the following function:
```
- (void)textViewDidBeginEditing:(UITextView *)textView
{
    if (_placeholderText && [textView.text isEqualToString:_placeholderText]) {
        textView.text = @"";
        textView.textColor = [UIColor blackColor];
    }
    [textView becomeFirstResponder];
}
```
- Input field background color changes based on the system theme instead of app theme
- Keyboard appearance changes based on system theme

These issues are critical when the user is on iOS 13 with System Dark Theme enabled.
PFA the screenshot:
drawing

### PR DESCRIPTION
**Pull request by jwoo-msft**
With iOS 13, Apple introduced a dark theme.
Changed Textview to update its text color according to the theme

## Related Issue
Fixed #4216
 
## How Verified
How you verified the fix, including one or all of the following:  
1. regression tests were run.
2. tested and visually confirmed that the change is good by changing system theme to dark mode, and ran the repro step.
IMG_D7DFFCC676F4-1

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4291)

### CODE REVIEW

File: source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm [hunk 1]
```diff
@@ -142,15 +143,25 @@ - (void)textViewDidBeginEditing:(UITextView *)textView
 {
     if (_placeholderText && [textView.text isEqualToString:_placeholderText]) {
         textView.text = @"";
-        textView.textColor = [UIColor blackColor];
+        if (@available(iOS 13.0, *)) {
```
Comment (shalinijoshi19) [inline source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm:146]: We should test both on iOS13 as well as previous versions - both to ensure no regressions.

Comment (shalinijoshi19) [reply source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm:146]: Additionally once this is in, do remember to cherry pick into release/1.2 branch.. thanks!
