### PR TITLE
[UWP][TestApp] Usability Improvements

### LINKED ISSUE #3045: [UWP][TestApp] Update the test app to better communicate what caused the card to fail
# Platform

What platform is your issue or question related to? (Delete other platforms).

* UWP

# Issue

Today the "Failed/source changed" results category doesn't specify whether it was the image or the json round trip that failed. This issue tracks making that clearer, and possibly additional refactoring of the implementation/UI for tracking test results.

### PR DESCRIPTION
**Pull request by RebeccaAnne**
Several improvements to the UWP test app.

- More information in test results. Specifically, calling out the results of original comparison, json round tripping and image comparison. In addition, added a colored border to call out whether the image comparison failed:

image

- Ability to accept originals, jsons, or images independently, both per card and for the entire list:

image
image

- As a result of those changes, we no longer need all of the combinations of tabs on the side. Simplified that list:

image

- To support these changes, changed the TestStatus from an enum to class, and updated the code accordingly.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/3046)

Fixes #3045

### CODE REVIEW

File: source/uwp/UWPTestLibrary/TestResultViewModel.cs [hunk 1]
```diff
@@ -317,41 +446,70 @@ private static string GetStoredSourceFileName(string name, string hash)
...
-        /// Visual did NOT match, but source files (payload and host config) changed, so changes are possibly expected
-        /// </summary>
-        FailedButSourceWasChanged,
-
-        /// <summary>
-        /// New test, no existing Expected
-        /// </summary>
-        New
+        // The error results match (either both pass or both fail with the same result)
+        public bool MatchedViaError { get; set; } = false;
```
Comment (andrewleader) [inline source/uwp/UWPTestLibrary/TestResultViewModel.cs]: NIT: Use the 3 slashes comments like `/// <summary>`, those will be picked up by IntelliSense so that when you're accessing these properties elsewhere, their summaries appear :)

File: source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs [hunk 2]
```diff
@@ -25,30 +25,47 @@ private void TestResultView_DataContextChanged(FrameworkElement sender, DataCont
...
 
-                if (model.Status == TestStatus.Passed)
+                if (model.Status.NewCard)
                 {
-                    ButtonSaveAsExpected.Visibility = Visibility.Collapsed;
+                    // For a new card, only let them update "all"
+                    ButtonUpdateImage.Visibility = Visibility.Collapsed;
+                    ButtonUpdateJson.Visibility = Visibility.Collapsed;
+                    ButtonUpdateOriginals.Visibility = Visibility.Collapsed;
+                    ButtonUpdateAll.Visibility = Visibility.Visible;
```
Comment (andrewleader) [inline source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs]: One thing I like to do for UIs like this is first set all the buttons to Collapsed, and then inside each logic branch, all you have to worry about is showing buttons, rather than both showing and hiding. Makes it a little cleaner (and reduces the chance of forgetting to collapse a button). But just a small nit :)

File: source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs [hunk 3]
```diff
@@ -25,30 +25,47 @@ private void TestResultView_DataContextChanged(FrameworkElement sender, DataCont
...
+
+                }
+                if (model.Status.MatchedViaError)
```
Comment (andrewleader) [inline source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs]: >if (model.Status.MatchedViaError) [](start = 16, length = 33)

Should this be an `else if`? I'm not sure, but seems odd having the two if statements next to each other?

File: source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs [hunk 4]
```diff
@@ -60,8 +77,30 @@ private void TestResultView_DataContextChanged(FrameworkElement sender, DataCont
 
         private async void ButtonSaveAsExpected_Click(object sender, RoutedEventArgs e)
         {
+            bool updateOriginals = false;
+            bool updateImage = false;
+            bool updateJson = false;
+
+            Button buttonSender = sender as Button;
+            if (buttonSender.Name == "ButtonUpdateOriginals")
```
Comment (andrewleader) [inline source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs]: >if (buttonSender.Name == "ButtonUpdateOriginals") [](start = 12, length = 49)

Instead of doing string comparison, you should be able to do the following... compare the reference

```
if (sender == ButtonUpdateOriginals)
```

That way it'll also be compiled and checked in case we ever rename the buttons :) The following could also work if the reference comparison provides a warning

```
if (buttonSender.Name == ButtonUpdateOriginals.Name)
```

File: source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs (hunk 2 above)
Comment (RebeccaAnne) [reply source/uwp/AdaptiveCardTestApp/Views/TestResultView.xaml.cs]: Sure

---
In reply to: [292200213](https://github.com/microsoft/AdaptiveCards/pull/3046#discussion_r292200213) [](ancestors = 292200213)
