### PR TITLE
[Android][UX] Fix Compact ChoiceSet size

### LINKED ISSUE #4891: [Android][UX] [Input ChoiceSet (compact) height and width squeezed]
# Platform

What platform is your issue or question related to? (Delete other platforms).

* Android

# Author or host

Microsoft Teams

# Version of SDK

SDK 2.1.0 (ACv1.3)

# Details

The height and width of the Input ChoiceSet (compact) is squeezed. The screenshot below shows the current user experience.

image

### PR DESCRIPTION
**Pull request by almedina-ms**
## Related Issue
Fixes #4891 

## Description
Compact ChoiceSets now have explicit layoutparams set to ensure width matches parent width

## How Verified
The fix was verified manually

image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4928)

### CODE REVIEW

File: source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java [hunk 1]
```diff
@@ -246,6 +248,8 @@ public View renderComboBox(
 
         final ComboBoxInputHandler comboBoxInputHandler = new ComboBoxInputHandler(choiceSetInput);
         final Spinner spinner = new Spinner(context);
+        spinner.getBackground().setColorFilter(Color.RED, PorterDuff.Mode.SRC_ATOP);
```
Comment (RebeccaAnne) [inline source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java:251]: >spinner.getBackground().setColorFilter(Color.RED, PorterDuff.Mode.SRC_ATOP); [](start = 8, length = 76)

For my own curiosity, what does this line do?

**Review by RebeccaAnne — APPROVED** [review]
:shipit:

File: source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java (hunk 1 above)
Comment (almedina-ms) [reply source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java:251]: that was a line that should not be there
