### PR TITLE
[JS Renderer] Fix toggleVisibility within showCard

### LINKED ISSUE #8086: [Authoring] Action.ToggleVisibility is not working within Action.ShowCard
### Target Application

Microsoft Teams, Outlook

### Application Operating System

Windows

### Schema Version

1.4

### Problem Description

Following an event, I contact my end-users to get answers. 
- Yes 
- No

If Yes, I want that they precise Option 1 or Option 2. 

To do this, I am using: 
- Two Action.ShowCard to display "Yes" and "No"
- Within the "Yes" Card, an Action.ToggleVisibility to select "Option 1" and "Option 2". 
- If I select "Option 1" or "Option 2" some text and a "Confirm" button shall be displayed. These elements are not visibile by default

However, when I put the Action.ToggleVisibility within a an Action.ShowCard there is no effect when I activate the Toggle. 

### Expected Outcome

When I activate an Action.ToggleVisibility action within the ShowCard, I should see the targeted elements. 

### Actual Outcome

I cannot manage to change the visibility of items within ShowCard. 

For example, in the code below I cannot change the visibility of "MyText 1"

### Card JSON

```JSON
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.4",
    "body": [
        {
            "type": "ActionSet",
            "actions": [
                {
                    "type": "Action.ShowCard",
                    "title": "Action.ShowCard",
                    "card": {
                        "type": "AdaptiveCard",
                        "body": [
                                {
            "type": "Container",
            "isVisibility": false,
            "id": "id11",
            "items": [
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.ToggleVisibility",
                            "title": "Action.ToggleVisibility",
                            "targetElements": [
                                "id1"
                            ]
                        }
                    ]
                },
                {
                    "type": "RichTextBlock",
                    "isVisibility": false,
                    "id": "id1",
                    "inlines": [
                        {
                            "type": "TextRun",
                            "text": "My Text 1"
                        }
                    ],
                    "isVisible": true

                }
            ]
        }
                            ]
                    }
                }
            ]
        }
    ]
}
```

### Repro Steps

_No response_

### PR DESCRIPTION
**Pull request by anna-dingler**
# Related Issue

Fixes #8086

# Description

We needed to override the `getElementById()` method for `ActionSet` and `ContainerWithActions`. If these elements contain a `ShowCard` action, we need to search `action.card` for the matching id.

# Sample Card

Added two samples cards. One for `ShowCard` within `actions[]` and one for `ShowCard` within an `ActionSet`.

# How Verified

Verified manually on the Designer and added two ui tests.

I also verified the test cases provided in #8086 and #8066

toggle

toggle2

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/8132)

### CODE REVIEW

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 1]
```diff
@@ -6537,6 +6537,26 @@ export class ActionSet extends CardElement {
...
+
+                    if (result) {
+                        break;
+                    }
+                }
+            }
+        }
+
+        return result;
+    }
```
Comment (beervoley) [inline source/nodejs/adaptivecards/src/card-elements.ts:6558]: this code is repeated twice - could you please refactor?
see if it can be placed in the parent class of the both classes where it's used?:)

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 2]
```diff
@@ -6537,6 +6553,16 @@ export class ActionSet extends CardElement {
...
     }
 
+    getElementById(id: string): CardElement | undefined {
+        let result = super.getElementById(id);
+
+        if (!result) {
+            result = this.getElementByIdFromAction(id);
+        }
+
+        return result;
```
Comment (beervoley) [inline source/nodejs/adaptivecards/src/card-elements.ts:6563]: this looks better:)
do we absolutely have to go over the tree **twice** in this scenario?
can we somehow detect this scenario in another way?

Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts:6563]: Do you mean call `super.getElementById` and `this.getElementByIdFromAction`?

Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts:6563]: If so, `getElementById` doesn't normally traverse the tree. It checks if the current element is the correct id :)

Comment (beervoley) [reply source/nodejs/adaptivecards/src/card-elements.ts:6563]: oh I see... the name of the method - `getElementById` doesn't reflect what it does then :D

File: source/nodejs/adaptivecards/src/card-elements.ts [hunk 3]
```diff
@@ -716,6 +716,22 @@ export abstract class CardElement extends CardObject {
...
         return undefined;
     }
+    
+    getElementByIdFromAction(id: string): CardElement | undefined {
+        let result = undefined;
+        for (let i = 0; i < this.getActionCount(); i++) {
+            const action = this.getActionAt(i);
+
+            if (action instanceof ShowCardAction) {
+                result = action.card.getElementById(id);
```
Comment (beervoley) [inline source/nodejs/adaptivecards/src/card-elements.ts:726]: do we only have the scenario when we need to pull the id of the action `only` when it's `showCardAction`? 
it's solving this particular issue, just want to make sure that we don't have any other potential scenario with other action types when we need to do the same thing:)

Comment (anna-dingler) [reply source/nodejs/adaptivecards/src/card-elements.ts:726]: Yup, showCardAction is the only action that has its own card as of now

**Review by beervoley — APPROVED** [review]
